### ISSUE TITLE
min from console, vimlike navigation

### ISSUE THREAD

**Issue by Marco-Israel** [minbrowser/min#1020]
Hello,

not an Issues, but dont know where its best to ask a question to you or start a discussion about improvements. 

I like your minimalistic web browser. But two questions for me are from interst:

How can I give a search term via console to min and mybe the search engine?

Like for example:
min https://minbrowser.org/
min searchme
min a search string
min -s "an other  string  in question marks via parameter"
min -e duckduckgo -s "yourstring"
min -e startpage -s "yourstring"

Cool would also be a vimlike hotkey binding and a manpage or -h to get options, keybindings etc via console

Kind regards

someone :)

**Comment by PalmerAL** [comment]
The URL example already works. I've added support for search parameters in f41f048c99451b978b807df4470ab665335b3d50, so these should work starting in the next version:
```
min "test search"
min -s searchquery
```

I don't think I'm going to support picking a search engine for now in order to keep this reasonably simple. If you use DDG, you can do this:
```
min -s "!sp search"
```
and it will redirect you.

There's a userscript you can install to get vim keybindings: https://github.com/palmeral/min-vim-mode

**Comment by Marco-Israel** [comment]
Thanks a for answering it :)
