### ISSUE TITLE
links leaving gmail are always blocked

### ISSUE THREAD

**Issue by genseric** [minbrowser/min#1029]
a new tab opens but it always is stuck with about:blank#blocked as address. 
legitimate domains like google.com are blocked too. 
min browser version : Version 1.14.1 (1.14.1)

**Comment by PalmerAL** [comment]
Clicking links inside emails works for me; is that not working for you? Or is there a particular link somewhere in Gmail that's not working?

**Comment by genseric** [comment]
![image](https://user-images.githubusercontent.com/649577/82852709-4daf9d00-9f0c-11ea-977a-7a7e777d2660.png)
once i click this link from google it opens a new tab with the address i wrote about above.
btw, my custom UA string is : 
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:74.0) Gecko/20100101 Firefox/74.0

**Comment by PalmerAL** [comment]
I can reproduce this with a custom UA enabled; it looks like gmail has some strange popup window code for Firefox that doesn't work in Min because of #140. It's probably possible to write a script that would work around this (like the existing ones in siteUnbreak.js); otherwise, switching back to the default UA should fix this.

If you want to use a custom UA so that google sign in works, one thing that was suggested in #893 is to use the Edge Chromium UA instead:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.37
```

which will probably get you the working gmail code.

**Comment by genseric** [comment]
Hey, very true. The UA string solved the issue. 
Thanks a lot.
