### ISSUE TITLE
allow opening of ftp://

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1049]
I think this will be useful sometimes...

**Comment by PalmerAL** [comment]
I think this is better handled by a dedicated client. Chrome is currently removing support for FTP, since only around 0.2% of their userbase used it ([link](https://www.bleepingcomputer.com/news/google/google-reenables-ftp-support-in-chrome-due-to-pandemic/)), and it would likely be a significant amount of work to maintain, so I don't think it's worth it.
