### ISSUE TITLE
chat sound in gmail window is not coming

### ISSUE THREAD

**Issue by raj123** [minbrowser/min#1051]

**Comment by raj123** [comment]
any update on this?

**Comment by PalmerAL** [comment]
This is an interesting problem. In order to get Google Drive to work, we emulate parts of the Chrome extensions API on all *google.com sites, but when we do this, Hangouts tries to connect to an extension (that doesn't seem to exist in the Chrome webstore) and breaks, which causes it to stop playing notification sounds.

Probably fixed in 806932b775741bc8dc5218cc1c9bb1d643faf486; let me know if it works again after the next release (hopefully it will!)

**Comment by raj123** [comment]
yes it is working now. Thanks.
