### ISSUE TITLE
Open tasks overlay by hovering mouse over tab bar

### ISSUE THREAD

**Issue by towerofnix** [minbrowser/min#106]
It might be nice if hovering over the tab bar for a moment would open up the tasks overlay, or perhaps have the overlay open when the control key is pressed _and_ the mouse is hovered over the tab bar..

(more or less copied from #105)

**Comment by code-hunger** [comment]
I think instead of opening the task overlay on navbar hover (which could be startling if you're reading something and have moved the mouse unintentionally up), it'd be better to open it when you hover the `view-tasks` button.
So that you move the cursor to the top-right corner, much like you show the desktop by moving cursor to bottom-right in Windows.

**Comment by antfu** [comment]
Closing this for now as it's being idle for a long while. If you still have the issue/request, please feel free to open a new one! Thanks.
