### ISSUE TITLE
increase size for microphone button

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1076]
I have been testing mic for a while now and there where a lot of missed clicks :d

i think it is too small and we should increase the size of the button... 

![image](https://user-images.githubusercontent.com/22417494/85075672-be766c00-b1cf-11ea-8fa3-dcf9ea6a2f48.png)

**Comment by Syndamia** [comment]
How do you want it to be bigger? It seems that heightwise it's as big as it can get, with the current tab system atleast. 

From [this comment](https://github.com/minbrowser/min/issues/1078#issuecomment-646933077) by @PalmerAL adding a big icon might not be possible right now.

**Comment by shalva97** [comment]
well, i would like it to begin at the start of the tab and end at the start of the page title...

**Comment by PalmerAL** [comment]
@Syndamia The other issue is about favicons from each website, not the permission button.

I think we could probably make the clickable area of the button extend a bit outside of where the button actually is - so that the button would appear the same size visually, but if you clicked near the edge of it, it would activate. However, that also increases the chances of someone accidentally clicking on the button, which might not be a good trade-off - accidentally enabling your microphone is probably worse than having to click a second time to enable it.

**Comment by shalva97** [comment]
okay, i agree missclicks will be worse... will close this, because i have no better idea...
