### ISSUE TITLE
Exiting fullscreen causes the top application menu to appear

### ISSUE THREAD

**Issue by nanaian** [minbrowser/min#1093]
The top [application menu](https://www.electronjs.org/docs/api/menu) appears when exiting fullscreen (i.e. press F11 or fullscreen a YouTube video, then hit Esc to reproduce). This isn't shown by default and there doesn't appear to be a way to get rid of it after it appears besides restarting Min, so it seems to be there in error.

Interestingly, the menu is similar to the three-dot menu, but the New Tab options are part of _File_ and the Bookmarks/History links are part of _View_. I assume this is to support macOS' global top bar, but should never be shown on Windows/Linux?

![Screenshot_20200625_002309](https://user-images.githubusercontent.com/9429556/85637180-68e00a80-b67a-11ea-9068-34d1d9ca0fad.png)

This happens on at least Linux - I haven't tested Windows and I expect its irrelevant on macOS.

**Comment by PalmerAL** [comment]
>  I assume this is to support macOS' global top bar, but should never be shown on Windows/Linux?

Yup - it's still attached to the window so that keyboard shortcuts work, but it's not supposed to be visible.

I think this is ultimately a bug in Electron - we call `setMenuBarVisibility(false)` when the window is created, but it looks like that only affects the current menubar state, and doesn't set any kind of flag on the window. Meanwhile, Electron has some separate code that hides the menu bar when fullscreen is entered and shows it again when fullscreen is exited ([here](https://github.com/electron/electron/blob/72a089262e31054eabd342294ccdc4c414425c99/shell/browser/native_window_views.cc#L558-L562)), but it ignores the fact that the menu bar was hidden even before fullscreen began.

However, it's probably easiest to just work around it by listening for the leave-full-screen event and hiding the menu bar again.

It seems to work fine on Windows - I think the visibility of menus there is controlled by the OS, and so it's always hidden in a frameless window regardless of what Electron does.
