### ISSUE TITLE
Block specific sites

### ISSUE THREAD

**Issue by Taktwerker** [minbrowser/min#1189]
It would be great if it would be possible to block specific sites completely with some kind of blacklist to reduce distraction, how browser plugins like [block site](https://addons.mozilla.org/en-US/firefox/addon/block-website/) (firefox) do. That would be a great digital minimalism feature :)

**Comment by PalmerAL** [comment]
If we don't make this a built-in feature, you could probably do it with a userscript, for example:

```
// ==UserScript==
// @match http*://example.com
// @run-at document-start
// ==/UserScript==

alert('site blocked')
window.location = "about:blank"
```

**Comment by Taktwerker** [comment]
Thank you for your answer. I´ve copied your example script as decribed under the path C:\Users\%Username%\AppData\Roaming\Min\userscripts into a file called blocksites
and edited the parameters. But if i want to block as example google.com it dosn´t work
(I activated the user script option and reopened the min browser before). Do i am anything
wrong?

// ==UserScript==
// @match http*://*.google.com
// @run-at document-start
// ==/UserScript==

alert('site blocked')
window.location = "about:blank"

**Comment by Syndamia** [comment]
@Taktwerker this should work for subdomains of `google.com`, like `mail.google.com`.

**If it doesn't work on subdomains**, the problem is probably with your file. Did you save it as a `JavaScript` file? Something like `website-blocker.js` should be your name. 

Just to be sure it isn't saved as a text file, turn on [file name extensions](https://www.tenforums.com/tutorials/62842-hide-show-file-name-extensions-windows-10-a.html#option1) and look at it again. If at the end there is `.js.txt`, then the file was saved as a `.txt` (text) file, so remove the `.txt` and restart the browser.

**Otherwise**, the problem is that you have `*.google.com`, which will block all subdomains of google like, `mail.google.com` or `drive.google.com`, but won't block `google.com` itself. 

The `*` means that there can be anything there, but after it there is a `.`, meaning just `google.com` won't be blocked because there isn't a dot in front of the word google.

Using `@match http*://*google.com` should block all google sites, including `google.com`.

**Comment by Taktwerker** [comment]
Thank you for your reply. I saved the script file in the wrong format (without extension). So now i saved it as ".js" file and it worked. Thank you for your help :) Can you integrate the info that it must be saved with the extension ".js" in the wiki article (https://github.com/minbrowser/min/wiki/userscripts)? So others can find that info too :)

**Comment by Syndamia** [comment]
> Can you integrate the info that it must be saved with the extension ".js" in the wiki article

I did with [this revision](https://github.com/minbrowser/min/wiki/userscripts/7e5baf785e32998d409ebc94b551a7f45ddcae8a) of the article.

**Comment by Taktwerker** [comment]
Looks fine. Thank you.
