### ISSUE TITLE
mute tab functionality should be in Task View

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1243]
there are few things that is bad and some questions, maybe few of them subjective but here they are

- lets say i have a video playing and then switched to another tab. why would i want to mute tab? This was added to Firefox and years passed without me ever using it.... I think if you gave users both pause and mute buttons everyone would press pause and never mute. 
- mute icon doesnot fit well with other UI icons. Looking at other icons gives me idea that Min has a specific icon style, which i would describe as hollow, with thin lines. But the mute icon is completely black.
expected style:
![image](https://user-images.githubusercontent.com/22417494/93188993-b4262880-f752-11ea-9221-fa69d3ca88a6.png)
reality:
![image](https://user-images.githubusercontent.com/22417494/93189177-e9327b00-f752-11ea-870d-d1fee7c1d7fc.png)
- lets say there are 4-5 tasks with about 30-40 tabs. if there is a tab that plays audio it will be hard to find and mute.

here is what i think will be best:
suppose you have audio playing in youtube tab, you will have mute, previous, pause and next button.
![image](https://user-images.githubusercontent.com/22417494/93190560-90fc7880-f754-11ea-8d1e-3fa85f76347b.png)

**Comment by shalva97** [comment]
one more small thing: mute icon doesnot have mouse hover state, for some people it will take more time to find out that they can press the icon...

**Comment by Syndamia** [comment]
I agree with some of what you are implying.

> I think mute tab functionality is useless

Useless is a bit too harsh. Underdeveloped, yeah, ok. You have some good arguments for it's functionality and look but there are cases where it is useful. Pausing sounds awesome, but if we have both icons, the page tabs will become pretty cluttered. 

Also, I'm not sure how "universal" pausing is, meaning probably different sites use different ways to pause so if we have some sort of system it might work only in certain cases. Considering that, I don't believe replacing muting with pausing is a good idea.

> why would i want to mute tab?

Muting is still useful for situations where you can't pause, for example while being in a voice call in the browser (although I haven't tested if it even works in that situation). As I discussed, pause might not be fully universal, in these cases muting is the only viable option.

> mute icon doesnot fit well with other UI icons

I mean, the way you have put them side by side, yeah, it looks out of place. In practice though, I find it fits fairly well:

![mute-dark-off](https://user-images.githubusercontent.com/46843671/93233579-e7cd7680-f783-11ea-9424-d1b615f7657d.png)
![mute-dark](https://user-images.githubusercontent.com/46843671/93233496-d08e8900-f783-11ea-9758-97f3602b0059.png)

Although, I do agree that your proposed icon will probably look better!

> if there is a tab that plays audio it will be hard to find and mute

I agree, I really like the idea of muting being an option in the tasks menu. I'm not sure if there is a good way to implement the previous and next buttons though.

> mute icon does not have mouse hover state

Yes, this should be fixed.

**Comment by PalmerAL** [comment]
There is a standard method to pause a video element: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause that should work in most cases. It's possible that sites that have custom video controls (like Youtube) might break if you call it unexpectedly though, so that would be worth testing. I don't know about the videoconference case either - that's something we would need to test.

I'm imagining a single button that would do the following:
* Call the mute() method on the webview
* Look through the webpage for any media that is currently playing, and pause it.
* Keep a list of which media was paused.
* When the button is clicked again, call play() on any media that was previously paused.

If you wanted to continue playing the video while keeping it muted, you could click the mute/pause button and then press the play button on the video again.

Having a button in the task list does sound nice.

Previous and next sounds pretty difficult; there isn't any standard API for that AFAIK, so you would have to implement it separately for each site you want to support (eg. creating a userscript or something just for youtube, etc.). I don't think it makes sense to include that as a standard feature unless we can find a better implementation.

**Comment by iFarhaan** [comment]
> why would i want to mute tab? This was added to Firefox and years passed without me ever using it.

Can't stop laughing at this point. People aren't fool to add such feature if it wasn't helpful.
> Muting is still useful for situations where you can't pause, for example while being in a voice call in the  browser.

It's exactly my point and moreover few site notifications also causes distraction where there is no play or pause except turn it off from the interface or settings. Muting tab is one-stop solution for that. Hope someday when you come across this situation you'll surely find it helpful.

**Comment by shalva97** [comment]
> Muting is still useful for situations where you can't pause

I dont know, maybe in a call it will be useful but some websites offer you to "put on hold". i mean, this is basic UX, you shouldnot need a specific browser functionality to fix it. In case of adds there already is adblocker and it should handle that.if it is still that annoying you should find another website, they dont deserve users.

Chrome and Firefox has "mute tab" on right click on the tabs. In case of Min this is not the case, so if there are notification sounds it will be hard to mute them because the moment they stop playing, mute icon goes away. restarting the browser also loses the state of muted websites, which also happens in Firefox but Chromium remembers it. in Min these things can be improved but is this really that important? 

@iFarhaan how many websites do you have muted right now? i have about 30 tabs open all day, and open&close many more but cannot find one that has so much bad UX that a browser should fix it for them.

![image](https://user-images.githubusercontent.com/22417494/93383769-2858ed00-f875-11ea-8e76-80cb727ac055.png)
that icons looks incredibly ugly, it takes so much precious space. @PalmerAL @Syndamia @iFarhaan people dont tell me that you are okay with this ugliness. 

> There is a standard method to pause a video element

yes, i just love this. right now im on KDE Plasma, they have Media Player icon in the tray that shows up everytime i have video playing inside Min. it allowed me to bound a keyshortcut globally and i can pause video even if Min doesnot have focus. This is  why i never need to mute a tab.

> Previous and next sounds pretty difficult; there isn't any standard API for that AFAIK

in Plasma sometimes it shows Next and Forward buttons on Youtube, not sure why it doesnot work always but it shouldnot be hard to add them in task list, i mean it is already there, right? this is what it [looks](https://user-images.githubusercontent.com/22417494/93386463-cbf7cc80-f878-11ea-8caa-8360285e605f.png) like.

> Look through the webpage for any media that is currently playing, and pause it.
Call the mute() method on the webview

no no please, it shouldnot do 2 things. It will be unexpected for many users and hard to find an icon that would give users a hint that it will pause and also mute the tab.

> I agree, I really like the idea of muting being an option in the tasks menu.

> Having a button in the task list does sound nice.

most of us agree, probably @iFarhaan will agree too. so these buttons, lets call them Media Buttons. should be in Task List. In fact, i will have nothing against mute icon if it wont be on tabs appearing, disappearing and taking space. 

do we all agree to do it? or at least change icon to be hollow so it wont stand out too much...

**Comment by iFarhaan** [comment]
> Chrome and Firefox has "mute tab" on right click on the tabs. In case of Min it is not

Yes, Min needs improvement that's why we are filling issues here. Long way to go.........

> that icons looks incredibly ugly, it takes so much precious space.

It can be tweaked.

> yes, i just love this. right now I'm on KDE Plasma, they have Media Player icon in the tray that shows up every-time i have video playing inside Min. it allowed me to bound a key-shortcut globally and i can pause video even if Min doesn't have focus. This is why i never need to mute a tab.

I also love **KDE** but here it is question of Browser not **DE**. We love KDE but people using **i3, Mate. GNOME, xfce4** and so on... what will they do? Everyone must not change **DE** for a cool feature.

> most of us agree, probably @iFarhaan will agree too. so these buttons, lets call them Media Buttons. should be in Task List.

Yes I'm strongly agree with that. It would be great.

**Comment by kodumbeats** [comment]
> I also love **KDE** but here it is question of Browser not **DE**. We love KDE but people using **i3, Mate. GNOME, xfce4** and so on... what will they do? Everyone must not change **DE** for a cool feature.

As an **i3** user, I have to admit that I've distro-hopped and DE-hopped for less. 🙃 

> so these buttons, lets call them Media Buttons. should be in Task List.
@shalva97 Do you have some suggestions for icon packs? I'm newer to min, so I'm not quite in tune with what the aesthetic should be.

**Comment by shalva97** [comment]
> people using i3, Mate. GNOME, xfce4 and so on... what will they do? Everyone must not change DE for a cool feature.

KDE is not doing anything special, they use [dbus](https://specifications.freedesktop.org/mpris-spec/2.2/index.html) to control media players. If you use i3 it shouldnot be hard to figure out how it works and write keybinds for it. forget DEs and WMs, they are off topic, i mentioned them as an example, they have media buttons already working...

> Do you have some suggestions for icon packs?

Min already has icons that are just lines or dots. Adding a sound icon that is completely black does not fit with any other icon. Google "hollow icons" or "line icons" and i would say all of the results you get are good. this [one](https://user-images.githubusercontent.com/22417494/93530927-76422380-f94f-11ea-9aa2-b321f2318590.png) looks good, and also [this](https://user-images.githubusercontent.com/22417494/93531158-d042e900-f94f-11ea-92aa-103ad21da617.png), but **not** [this](https://user-images.githubusercontent.com/22417494/93531232-ed77b780-f94f-11ea-90e6-56d07701e5b3.png).

people want to be able to mute tabs and there where few good arguments for it and it is already implemented. I will update the name of this issue and lets forget play/pause for now, just improve the mute functionality... who knows maybe i will also start using it.

**Comment by PalmerAL** [comment]
This issue is getting fairly unfocused, so I'm going to try to summarize what's been brought up so far:

### Mute button styling

* Icon - I agree a less-solid icon might be nice. If there's one that's available in an SVG and has suitable licensing we can definitely try it.
* It might also help to make the existing icon a bit smaller.

In a situation where every tab has a mute button, they do take up a lot of space, but I don't think that's a very common situation - it doesn't make much sense to have 5 different tabs all playing sound at the same time. Most commonly, you would just have 1 or 2 mute icons, so I'm not hugely concerned about the space usage.

### Previous and next track

Completely by coincidence, I just found out yesterday that there is a [new API](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession) that was just added to Chromium recently for this, which is why this works in standard Chromium. So I think this should be possible, although there's currently no Electron API for it, so we'd need to re-implement it in the preload script.

**Comment by shalva97** [comment]
> If there's one that's available in an SVG and has suitable licensing

im know little about licensing, or which one we need.... will research how this works later. but the icon looks simple so maybe i can paint one myself after few tutorials of Inkscape. 

> we'd need to re-implement it in the preload script

how hard could this be, maybe it is better to wait? at least in this issue lets just focus on Mute tab functionality. Will create another issue for other buttons.

for the mute button this is what i think should change:

- it should be in Task View, so it will be easier to find which tab is playing audio if you have lot of Tasks.
- when you hover over the tasks, mute icon should show up next to X icon, allowing you to mute even if the tab is currently not playing audio
- change the icon (i think i will have time this weekend to paint, but not sure about this, maybe it is easier to find one?)
- if browser closes, save muted states for tabs if they are still open. but which is better to save mute state for specific tabs or websites?
- also, mute icon should not show up on tabs, only in Task View. but his could confuse some users, because if they mute a tab and forget, it will not be easy for them to figure it out. so i dont know what to do here, i just dont like mute icon in tabs...

**Comment by shalva97** [comment]
Already found an issue for the other buttons https://github.com/minbrowser/min/issues/704

**Comment by shalva97** [comment]
okay, i gave up creating new icon. To learn how to draw icons takes more time and effort than i expected...

but i found this [material icons](https://material.io/resources/icons/?style=outline):
![image](https://user-images.githubusercontent.com/22417494/94370029-5b657100-00fe-11eb-83a7-a29f0135cfb2.png)

> Our icons are free for everyone to use. Please don’t try to sell them.
> Available under Apache license version 2.0.

what do you think @PalmerAL can we use that icons?

also these two from [here](https://www.flaticon.com/packs/music-29#):
![image](https://user-images.githubusercontent.com/22417494/94370316-53a6cc00-0100-11eb-82fd-8bfcbf4f0b32.png)

> Free for personal and commercial purpose with attribution.

I guess we can use both, hopefully there are no hidden terms. so what do you think?

**Comment by PalmerAL** [comment]
For the icon, I just realized that the icon set we're using already has an alternative icon that's an outline, which I didn't notice:

<img width="323" alt="Screen Shot 2020-09-27 at 8 17 04 PM" src="https://user-images.githubusercontent.com/10314059/94381285-720bc800-00fe-11eb-9e56-1019ed8338d5.png">
<img width="335" alt="Screen Shot 2020-09-27 at 8 16 55 PM" src="https://user-images.githubusercontent.com/10314059/94381286-72a45e80-00fe-11eb-82e0-5f7dedb4dc8f.png">

So it would probably be fine to just use that.

> if browser closes, save muted states for tabs if they are still open. but which is better to save mute state for specific tabs or websites?

Yeah, restoring the muted state for tabs makes sense to me.

> also, mute icon should not show up on tabs, only in Task View

One of the main use cases for this feature (I think) is to have a way to quickly stop audio that started playing unexpectedly, particularly in a situation where other people are listening to your computer audio (ex. sharing your screen over a video call). So having it in the tab bar is important so that you can click it quickly - if it was hidden in the task overlay, it would be much slower to use.

**Comment by shalva97** [comment]
> already has an alternative icon that's an outline

cant wait until it is changed.

> having it in the tab bar is important so that you can click it quickly

yeah.... I agree... but I still dislike it. but if it will be there i think that it can be improved.
also add mouse hover state, save mute state for tabs and it will be better!

**Comment by PalmerAL** [comment]
1d3130b31b66a337b4300b74f0873178897ade7f changes the icon, adds a hover effect, and remembers the muted state of a tab; I think that's everything that needs to be fixed here for now, since there's another issue open for the task overlay.

**Comment by shalva97** [comment]
Thanks @PalmerAL you are awesome!!
