### ISSUE TITLE
Downloading from Google Docs as PDF fails

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#1266]
<img width="532" alt="Screen Shot 2020-10-04 at 6 37 58 PM" src="https://user-images.githubusercontent.com/10314059/95029838-d08df480-0670-11eb-89c1-bb7c048e1514.png">

**Comment by MarkWahlsten** [comment]
Same issue with Docs/Drive 

Also happens when downloading a PDF attachment in gmail.

**Comment by MarkWahlsten** [comment]
This leads to a seperate issue, but I couldn't find the right one to post it:

Better workaround with less steps would be to open the attachment in Acrobat directly from gmail, but the new window gets blocked (about:blank#blocked).* 

Tried (but didn't work): 

- turn off "block popups" shield icon for gmail, in url bar
- dialled pop-up blocking preference back to "third-party only"

I came across the closed #1029 thread that highlights this issue, but the solution kinda went over my head. I get the feeling this has been solved, and I'm just not using the features correctly. 

_*This also happens when opening urls in Google Calendar events. My workaround is right-click > open, but that only works for Google Calendar._

**Comment by PalmerAL** [comment]
* The PDF download issues are fixed in the linked commit.
* The google calendar issue is fixed in 5fa3bd2e34740db9170263155c8f0a6b1e4ca8e1.

I'm not seeing an Acrobat addon in the gmail addon list - what exactly are you using?

**Comment by MarkWahlsten** [comment]
@PalmerAL –  Awesome! Thanks!

I think Acrobat may be a Google Drive add-on.

- I came across it when I opened a PDF link in Gmail, and clicked the "Open with" dropdown at the top. (Either under "third party apps" or "search more apps".

**Comment by shalva97** [comment]
This should be fixed in 1.18.1 right? 

Heres what happens to me:
Created a Doc, File > Donwload > PDF > click save button > download fails

**Comment by PalmerAL** [comment]
Hmm, it works for me. Which save button are you using? How does it fail?

**Comment by shalva97** [comment]
I dont know why but cannot reproduce this anymore :(

**Comment by PalmerAL** [comment]
Well let me know if it happens again.

One thing I've seen before is that Google docs' PDF generation is pretty slow, so there can sometimes be a lot of lag, both when going to file > download, and then again when saving the PDF. If you aren't seeing any response, maybe just try waiting longer.
