### ISSUE TITLE
Feature request : Bookmarks bar

### ISSUE THREAD

**Issue by Milo123459** [minbrowser/min#1271]
Nothing else to say, I think a bookmark bar would be a cool addition to min.

Let me know what you think! I hope this can be added.

**Comment by Milad-Laly** [comment]
@Milo123459 As far as I'm aware you can access your bookmarks through the searchbar using "!bookmarks".

@PalmerAL I'm not sure what you have planned but I could try and implement this?

**Comment by PalmerAL** [comment]
I'm inclined not to do this, since I don't think it makes sense to take up more space in the tab bar in most cases, and I don't think the increase in complexity is worth it. What I'd eventually like to do is make the initial data shown when you open the searchbar more useful, so that you could click on it and get to your top sites directly from there.

> @PalmerAL I'm not sure what you have planned but I could try and implement this? Also @PalmerAL is there a slack or an easier way to contact everyone else?

That's a good idea. I just made a discord server: https://discord.gg/bRpqjJ4 - does that work?

**Comment by Milad-Laly** [comment]
It worked and I'm closing the issue as it's explained why this would not be implemented. But, a similar feature will be implemented.
