### ISSUE TITLE
when searching from dev-tools and closing it, web page scrolls to top

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1280]
* **Min Version:** 1.16.0
* **Operating system:** Arch

## Expected Behavior
when searching in dev-tools "element' tab and closing dev-tools, the website should not scroll to top

## Actual Behavior
I saw Arch wiki references to my repo and decided to search where they linked my repo. the name of my repo was not visible so i searched with dev-tool's element tab, which it found it. that was awesome, there is my repo linked in Arch wiki :D

## To Reproduce
go to some website that has scrollbar. search something inside devtool's Elements tab and then close dev tools, it will scroll to top.

for example go to [here](https://wiki.archlinux.org/index.php/KDE) and search "shalva97" and then close devtools

**Comment by PalmerAL** [comment]
I think this is probably expected behavior; when you search for something, the devtools will scroll to the first element matching the search. I can't reproduce the exact behavior described - when I search for "shalva97", the page scrolls to the link, but if i search for just "sh" the page will jump to the top.

**Comment by shalva97** [comment]
no no. when you search and the page scrolls, then close devtools

In chromium scroll stays where it was, but in Min it scrolls to the top

**Comment by shalva97** [comment]
#1411 has simpler steps to reproduce this so I will close htis one
