### ISSUE TITLE
Tab close button should have margins on top

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1287]
**Can you describe the problem you're facing?**
it is easy to missclick close icon, also i remmember it had margins before...

according to [fits law](https://www.youtube.com/watch?v=95RoKSFyQ_k) close button has infinite size, so if you move your mouse to top it just stops and it is hard to miss.

also close button is invisible unless i hover over it, so if i want to quickly switch, i should first hover and see if my mouse is not over close button.

if there are more tabs, there is more chances to missclick

**What solution would you like?**
add top margin to close button. most of the browsers like FIrefox or Chromium also has margins.

**Are there any alternatives you've considered?**

**Comment by PalmerAL** [comment]
New dimensions, clicking on the orange area will select the tab instead of closing it:

<img width="83" alt="Screen Shot 2020-11-05 at 6 21 21 PM" src="https://user-images.githubusercontent.com/10314059/98311054-100f6f80-1f94-11eb-84f8-9859dea2999e.png">

I'm not sure how much that helps with the issue of the button appearing suddenly in general, but if you move your mouse to the top of the window while it's in fullscreen, it should work now.
