### ISSUE TITLE
acid3.acidtests.org errors

### ISSUE THREAD

**Issue by TraderStf** [minbrowser/min#131]
Hello,

Few errors on this test.

http://acid3.acidtests.org/

**Comment by cryptobird** [comment]
hmm, mine showed 100/100 on it.

**Comment by PalmerAL** [comment]
I think @TraderStf is referring to this text in the corner: 
<img width="132" alt="screen shot 2016-05-07" src="https://cloud.githubusercontent.com/assets/10314059/15092927/b7879024-143d-11e6-99c1-105f6d235420.png">

This is a chromium issue, though. I think it's fixed in Chrome 50, so hopefully electron/electron#5322 gets merged soon.

**Comment by TraderStf** [comment]
The test is not always 'clear'...
It crashes safari but you get 100/100 😇

**Comment by PalmerAL** [comment]
This still doesn't work, but since there's nothing we can do about it (it's a Chromium issue and happens in Chrome as well), I'm going to close this.
