### ISSUE TITLE
Search in page feature bugs

### ISSUE THREAD

**Issue by OlivierLapraye** [minbrowser/min#139]
Hi ! 

I've been using MinBrowser since.. today, and I've noticed that the "Search In Page" feature is pretty buggy. Let me explain : sometimes it works well, but sometimes when I'm searching for something, it finds way more results than expected. I even found some results in a page that didn't contained any of the provided string. I compared the same page with Chrome to be sure, and now I am !

The problem is that it seems to happen randomly, I haven't found any pattern when the results are wrong.

And another thing, when we browse across the iterations of a result, I think it would be cool to be scrolled down or up to the active iteration.

I hope this issue hasn't been reported yet, and let me say I love your work :)

**Comment by PalmerAL** [comment]
I think I've fixed the first issue in cb1015e6e3c28d76cb55a33eb5c509fce3a41fcd. The problem was that the count would not change if there were no matches. So, for example, if you searched for "min" on this page, you would get 4 matches, but if you then added an "n" and searched for "minn", "4 matches" would still be shown, even if there were zero matches. 

> And another thing, when we browse across the iterations of a result, I think it would be cool to be scrolled down or up to the active iteration.

It already scrolls to the current match, for me at least. If it's not for you, could you please share what platform this is happening on?

**Comment by OlivierLapraye** [comment]
I noticed it but it's only happening when there are "fake results", so solve the first issue will automatically solve the second !
