### ISSUE TITLE
Improve window.open support

### ISSUE THREAD

**Issue by Smona** [minbrowser/min#140]
When trying to download a free song from toneden.io, the page which redirects from a soundcloud verification gets stuck, making it impossible to download. 

[Example of where this happens](https://www.toneden.io/infuze/post/flosstradamus-roll-up-baauer-remix-infuze-re-roll)

**Comment by PalmerAL** [comment]
I'm guessing this is probably because we don't support window.open very well.

**Comment by miere** [comment]
The same happens on many sites when I try to use Facebook or Twitter login integrations...

**Comment by PalmerAL** [comment]
from #446:

> Site netlify.com (and many others) do authentication after logging in in the new window and refreshing the main window.
> 
> Problem:
> window.opener is nuil.
> 
> See
> 
> electron/electron#9533
> electron/electron#9961
> jiahaog/nativefier#164

**Comment by igk1972** [comment]
May by better migrate to https://github.com/brave/muon as framework ?

Muon is a fork of the Electron framework.
Some of Muons goals include:
- add security focused features for the renderer:
   - scriptable **window.opener support**.
   - **full sandbox**.
   - remove node completely (from the renderer process).
- faster and more streamlined end-to-end build process.
- use the Chromium source directly (eliminating electron's copy of chrome_src) with minor patches
make integrating chrome components less painful.

**Comment by PalmerAL** [comment]
@igk1972 see #440:

> Muon does seem to solve a lot of the issues with this (and support for popup windows would be nice as well). The biggest problem with Muon (and what's stopped me from considering a switch in the past) is that there seems to be almost no documentation on it. Brave's added a bunch of API's specific to their browser, and changed a bunch of things about how Electron's existing features work, and the only way (unless I'm missing something?) to figure out how to use it is to look at Brave's source code and guess what the correct API is. Meanwhile, glancing through their issue tracker, they don't seem to answer questions about it (which I completely understand, they're not obligated to, but it's a problem for us). If we migrate to Muon, I think we're going to have a lot of problems with this; I'm not really sure what the best option is here.

**Comment by PalmerAL** [comment]
But I do agree that Muon has a lot of advantages, maybe it's worth trying to figure out how to use it based on the Brave source code.

**Comment by dbfreem** [comment]
Is this still something being considered? I ran into a situation today where popups not being supported was a blocker for me using min.

**Comment by PalmerAL** [comment]
I'd like to have this too, but I'm not sure how feasible it is. We might be able to hack something together using preload scripts, and send synchronous IPC messages between the parent and the child window, but I'm not sure how well it would actually work. If it doesn't, then this would need to be implemented in Electron, which I think would require some pretty significant changes to Electron (although I'm not sure exactly what changes would be required). If someone wanted to work on it, I'm guessing they'd be willing to support it, but it doesn't seem to be a priority for anyone contributing to Electron right now.

**Comment by lawrencenull** [comment]
It seems electron does natively support window.open now through several methods.

https://electronjs.org/docs/api/window-open

**Comment by PalmerAL** [comment]
Oh, wow, you're right; everything does seem to work as expected when using the `nativeWindowOpen` option. (I'm wondering if that changed at some point, because I'm almost certain I tried that before, but maybe I'm just remembering wrong?)

**Comment by lawrencenull** [comment]
They changed it at some time or another. I was having the same problem a few months back and ran into this.

**Comment by larskouwenhoven** [comment]
Is there any outlook on a solution to this issue? It's the one reason keeping me from switching to Min, since I e.g. use Feedly on a daily basis, and cannot log in now.

**Comment by PalmerAL** [comment]
It works if you add `nativeWindowOpen: true` [here](https://github.com/minbrowser/min/blob/master/js/webviews.js#L171) and remove [this](https://github.com/minbrowser/min/blob/master/js/browserUI.js#L173-L183). However, I don't think we actually want websites to be able to open arbitrary popup windows, since that's easy to abuse. Ideally, we could make the new window open in a tab, but Electron doesn't support that right now; I'm not sure how much work it would be to implement. Alternatively, we could make a popup blocker, and require you to give permission to websites before they can open popups. I think that would be simple-ish to do, although it would be rather annoying to use.

**Comment by BenStigsen** [comment]
I think the permission popup would be the best approach or some setting that allows popups globally. Because having to mess with the code to be able to access sites that require Google authentication popup doesn't seem very user-friendly.

**Comment by sgreenden** [comment]
I can't log into Rateyourmusic.com

**Comment by PalmerAL** [comment]
1.5-ish year update on this: A few months ago, Electron got an (unofficial, unsupported) [option](https://github.com/electron/electron/pull/26802) to open popup windows as a BrowserView, which would allow them to act like a normal tab. This would address the issues with supporting popup windows that I previously mentioned.

I tried implementing it, and it mostly works, and solves the compatibility issues. However, it's fairly buggy - preload scripts don't always run, and closing a popup window will sometimes cause the whole app to crash (which someone else [also reported](https://github.com/electron/electron/pull/26802#issuecomment-835326046)).

(If anyone wants to try it out, it's here: https://github.com/minbrowser/min/tree/popup-window-exp)

If that doesn't work out (which it looks like is the case; I don't think it's acceptable to ship that with the current level of bugginess), then the options are:

* Allow every site to open "normal" popup windows (which create a new window instead of a new tab). These are well-supported by Electron, but a) we lose the ability to display a browser UI around them, and b) this breaks some other sites, which use `window.open` as a way to create new tabs, and so creating an actual window doesn't make sense.
* (What I'm planning to do now) create an exception for auth providers (google accounts, github, etc.) which allows links to those auth pages to open as a popup window. Everything else gets opened in a new tab as it currently does.
  * Benefits: Solves the majority of the issues reported here, avoids the risk of crashes and using unsupported features of Electron.
  * Downside: some sites will still be broken.

**Comment by VasylTyshchuk** [comment]
This browser looks amazing and it's very comfortable. But this bug stops me from using this program because I can't sigh in to many sites. I hope this will be fixed in the near future.

Does anyone know a similar minimalistic browser without bugs?

**Comment by PalmerAL** [comment]
This was fixed in the latest release 🎉

The approach I mentioned above turned out to not be as buggy as I thought, and so I finished off the implementation and released it. Most of the issues mentioned here should be fixed now. If you see any more, please let me know or open a new issue!
