### ISSUE TITLE
video does not load on edx.org

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1413]
- **Min Version:** latest commit about crash reporting
- **Operating system:** Arch KDE

## Expected Behavior
videos should play 

## Actual Behavior
video doesnot load with  these errors. But it works on Chromium with uBlock
![image](https://user-images.githubusercontent.com/22417494/103385947-10e8fb80-4b16-11eb-8623-aac35a423e93.png)

## To Reproduce
go to [this](https://www.edx.org/course/mandarin-chinese-level-1) website and try to play the video

**Comment by shalva97** [comment]
still suffering by this, any updates?

**Comment by PalmerAL** [comment]
Will investigate soon.

**Comment by PalmerAL** [comment]
You can also reproduce with the "simple" example from here: https://github.com/videojs/videojs-youtube

**Comment by shalva97** [comment]
what?

**Comment by PalmerAL** [comment]
I'm just making a note for myself if I look back at this later; that page has the same issue, and it's easier to debug that than the original link.

**Comment by PalmerAL** [comment]
The issue here is that we disable autoplay by default [here](https://github.com/minbrowser/min/blob/master/js/webviews.js#L206). There's normally an exception where clicking on the video allows autoplay for that site, but this site has a weird video player (where it displays a static image, then loads youtube when you click on it, then waits for the video to start playing, and then hides the image) that prevents that from working.

Ideally, they would fix their video player, but since that's unlikely to happen, I guess we should bring back this old PR: https://github.com/minbrowser/min/pull/1141/files and add a setting to enable autoplay.

**Comment by shalva97** [comment]
wow

**Comment by PalmerAL** [comment]
PR: #1550

(Does Github send a notification if I mention this issue in the other PR? I'm not sure).

**Comment by PalmerAL** [comment]
This is fixed as well as it can be for now - if you enable the setting, the site will start working.
