### ISSUE TITLE
Cookie consent isn't clickable on some sites

### ISSUE THREAD

**Issue by Syndamia** [minbrowser/min#1416]
- **Min Version:** 1.17.3
- **Operating system:** Fedora 33

## Expected Behavior

Going to any site, the popup box for giving cookie consent is clickable.

## Actual Behavior

On some sites, the box isn't clickable and makes me move the whole window.

![Peek 2021-01-04 10-11](https://user-images.githubusercontent.com/46843671/103514462-59394e00-4e75-11eb-9d25-d9e8e2a7f1c1.gif)

## To Reproduce

1. Go to https://smallseotools.com/small-text-generator/ (I've experienced it on other websites, but I don't remember on which)
2. Try to click the consent box (or anywhere in the page really)

**Comment by shalva97** [comment]
duplicate of #1381

**Comment by Syndamia** [comment]
Thanks, I forgot about that issue

**Comment by PalmerAL** [comment]
I think 1381 should be fixed soonish by an Electron update, but that issue seems to only affect content around the edges of the window, which this isn't. I guess see if this still happens in the next update and LMK if it's still happening.

I'm in the US, so I don't get shown the consent popup to test it. It seems odd that this would only happen on a specific site, but I'm assuming it doesn't happen on every page or you would have noticed a lot sooner.
