### ISSUE TITLE
"npm install" failed! ".nvmrc" probably needs update. What's the minimum version of node is required?

### ISSUE THREAD

**Issue by ylu02** [minbrowser/min#1474]
Hi, just found minbrowser and love it! Already found something that I feel I can contribute (bugs and translations). However, I'm currently stuck at "npm install" ........ Any help would be very much appreciated. Below is the basic environment:

- OS: macOS Catalina 10.15.7
- `nmv` is installed and and node is set to `8.1.4` automatically as specified by `.nvmrc`.
- `xcode` installed (full installation) and `SDKROOT` is set to `SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk`

When I run `npm install`, I'm getting the following error (part of the error output):

> keytar@7.3.0 build /Users/yulu/Workspace/minbrowser/node_modules/keytar
> node-gyp rebuild

```
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: glob dependency not found, set `options.disableGlob = true` if intentional
gyp ERR! stack     at defaults (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/node_modules/rimraf/rimraf.js:42:11)
gyp ERR! stack     at rimraf (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/node_modules/rimraf/rimraf.js:60:3)
gyp ERR! stack     at clean (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/lib/clean.js:11:3)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as clean] (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:41:37)
gyp ERR! stack     at run (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:80:30)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:95:7)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:161:9)
gyp ERR! stack     at Function.Module.runMain (module.js:607:11)
gyp ERR! stack     at startup (bootstrap_node.js:158:16)
gyp ERR! stack     at bootstrap_node.js:575:3
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/yulu/.nvm/versions/node/v8.1.4/bin/node" "/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yulu/Workspace/minbrowser/node_modules/keytar
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! keytar@7.3.0 build: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the keytar@7.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

I tried to remove, reinstall, update `node-gyp` but no luck so far. It always fail for the same error. Really ran out of ideas. Can anyone help?

Thanks in advance!

**Comment by ylu02** [comment]
OK, got it work by using newer node (v15.4.0 is the latest I've installed). 

I guess `.nvmrc` needs to be updated. Anyone know what's the minimum version of node is required?

**Comment by PalmerAL** [comment]
Oh, that's a silly problem; I don't actually use nvm, and I guess no one else is either.

It's probably fine to just set it to v15.

**Comment by ylu02** [comment]
Well, apparently there are people using nvm, especially considering people usually working multiple project (work, home) at the same time. 'nvm' (or any other version manager would be very helpful in this case.

Does anyone know the minimum required version?

**Comment by ylu02** [comment]
Looks like Min is currently on Electron 11, which should be using Nodejs 12.18.3, [as published here](https://www.electronjs.org/blog/electron-11-0).

Should we update `.nvmrc` to `12.8.3` then (I've only tested it on MBP though)?

**Comment by PalmerAL** [comment]
Oh I just meant people working on this project, based on the fact that no one noticed.

The Electron node version is independent of the development environment anyway - code in the app uses Electron's bundled node, while the dev scripts use the version from nvm. So it doesn't really matter what we pick; I'd probably just go with the latest version.

**Comment by ylu02** [comment]
I'd suggest to keep the two node versions (the one bundled with Electron and the one used by every dev locally whatever it is) the same, because you wouldn't want to work against a different set of API than the one that's going into production. 

I know the API is probably backward compatible most of the time, but you never know. And if you are developing using an older node (e.g. v11 as appose to v12) you could be missing new features that are available now. 

And it also benefits people who are using nvm, which is pretty popular I believe.

**Comment by PalmerAL** [comment]
You'll never write code for one that ends up being executed by the other; if you're writing code for the app, it will always be executed using Electron's node (and never the local one), and if you're working on the build scripts, they'll always be executed using the local node (and never inside Electron). But I guess we can just make them the same anyway.

**Comment by yulucodebase** [comment]
Hey, It's me again, using my personal github account.

I think I get what you meant, however, I think it probably needs a bit more clarifications, especially given this is an open sourced project. I mean, even if it's not open source, it should apply to any project in a team environment.
> You'll never write code for one that ends up being executed by the other;  

I thought it's exactly the opposite to the above statement. Everyone is running the code written by other people, even though the production code will evenly be running in the same Electron "container". I could be contributing code written on Nodejs v11 (instead of 12, as long as it works), someone else could be contributing code written on Nodejs v15 (latest).

Another point is that I think the definition of "code" should also include "build scripts", "configurations" and any other tools that are shared via the repository, i.e. nvm configurations in this particular discussion.

>if you're writing code for the app, it will always be executed using Electron's node (and never the local one), and if you're working on the build scripts, they'll always be executed using the local node (and never inside Electron). 

For production code at runtime (v12), it'd be better to be developed using the same Nodejs by the developers. For example, if I'm using Nodejs v15 (latest for now), how can I be sure it's will be 100% working as I expected on Nodejs v12 (Min)? What if I'm calling a new API that does not exist in v12? Or What if the implementation of a function call is changed in v15 and now has side effects which are not what we want? 

In the reverse scenario, in which I'm using an older version of Nodejs to develop the app running on a newer version of Nodejs, how can I take advantage of new APIs or features in the newer version.

Of course there are practice (e.g. `unit testing`, `CI` and using `.nvmrc` is actually another one)  that can prevent or reduce the aboves to happen, but it'll be up to individual developers to use them if you don't enforce these practice. It is just potentially problematic down the line once you have more people contributing, and more features are added. 

>But I guess we can just make them the same anyway.

I think the purpose of the `.nvmrc` is very similar to what "package.json" is for. Both are trying to remove unambiguity in the development environment. They increase predictability of the code, and ultimately decrease potential conflicts, incompatibility in the code. `nvm` also increase developer productivities so that we don't have to figure out which Nodejs to use for which project, similar to what "package.json" does to each dependencies. Even for people that are **not** using `nvm`, they can easily find out the correct Nodejs to use by looking at `.nvmrc`.

Sorry about the long read, but I just thought it's important to have an agreement on how to have a common development environment, especially for an open source project that has a lot of contributors. I guess I'll raise a PR later today and hopefully we can come to an agreement WRT this. 

I really like Min. Great works so far and hope it will be getting better and better!
