### ISSUE TITLE
Change the keyboard shortcuts

### ISSUE THREAD

**Issue by PalmerAL** [minbrowser/min#149]
The current keyboard shortcuts don't work very well (see #136, #130). I think something like the following might work better:

| shortcut | action |
| --- | --- |
| mod+n | new task |
| shift+mod+n | close current task |
| mod+t | new tab |
| shift+mod+t | new private tab |
| shift+mod+n | new private tab |
| mod+` | next task (same as Firefox) |
| shift+mod+` | previous task (also the same as Firefox) |

According to <a href="https://duckduckgo.com/?q=firefox+cheatsheet&ia=cheatsheet&iax=1">DuckDuckGo</a>, the mod+` shorctuts are only available on "some keyboard layouts", so I guess they conflict with something. Does anyone know what those keyboard layouts are?

**Comment by cryptobird** [comment]
I'm guessing sure by mod you `⌘`, though it's also used to refer to `⌥`.

I really like the idea of `⌘⇧N` opening a new task with your current tab as the first tab; I have a habbit of starting looking for something and adding it as a task later. `⌘W` already closes tabs, so why not have `⌘⇧W` close a task? 
I like the idea of ``⌘` `` cycling through tasks, but if it's not a available to everyone, other options are:
`⌘[` and `⌘]`
`⌘\` and `⌘⇧\`
`⌘/` and `⌘⇧/`
And/or, since tasks can be named, task switching could be built into the custom !commands ticket.
!n or !name could put you into that task.

**Comment by rafaelrinaldi** [comment]
@PalmerAL @cryptobird The problem with `⌘[` and `⌘]` is that, Firefox and Google Chrome users would expect it to be navigation between tabs.

**Comment by mardukbp** [comment]
@PalmerAL In most Latin languages the backtick is used as an accent and therefore it is a dead key. I guess Firefox uses localization to configure useful shortcuts for different languages.

I suggest using `Alt+o` and `Alt+i` for next and previous task. They are close to the home row :)

And definitely `mod+n` should not delete all tabs.

**Comment by edmundlaugasson** [comment]
I totally agree and kindly ask you to consider of changing keyboard shortcuts.
Currently there you cannot use text cursor move keys: CTRL+arrow keys for example but not only. Instead of keys moving in browser when to write e.g. email then it starts moving back and forth in browsing history and my written mail will be saved as draft if I am lucky.

**Comment by PalmerAL** [comment]
@edmundlaugasson What website is this happening on? If you try to type in a website with a normal text input (like Github's search box) does it still happen? Besides ctrl+arrow, what other shortcuts is it happening with?

These shortcuts are supposed to detect when an input is focused and not navigate back, so it would be nice to figure out why that isn't working.

**Comment by edmundlaugasson** [comment]
> What website is this happening on?

Google Mail (GMail). Haven't tested it in any other mail service.

> If you try to type in a website with a normal text input (like Github's search box) does it still happen? 

No - here in Github it does not happen.

> Besides ctrl+arrow, what other shortcuts is it happening with?

Moving in history back and forth in case of GMail. Basically it will open previous or next email/view I have opened before.

> These shortcuts are supposed to detect when an input is focused and not navigate back, so it would be nice to figure out why that isn't working.

Perhaps [GMail shortcuts](https://support.google.com/mail/answer/6594?co=GENIE.Platform%3DDesktop&hl=en) will help, although I did not find any such shortcut that consisted CTRL+arrow there.

**Comment by PalmerAL** [comment]
@edmundlaugasson Thanks, this should be fixed in f9705c1c6d6499217977973e6c928ab7ba6e9168.
