### ISSUE TITLE
useless hiidden element on error pages

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1490]
- **Min Version:** 1.17.3
- **Operating system:** Arch

## Expected Behavior
Error pages should be simple without extra stuff

## Actual Behavior
there is a checkbox like thing below error title
![image](https://user-images.githubusercontent.com/22417494/106956125-954f1f80-674f-11eb-9343-609462d048a4.png)

## To Reproduce
go to [this](https://developer.android.com/guide/components/activities) website to cause error and click somewhere there as in the pic

**Comment by Milo123459** [comment]
Not useless. I looked through the code and saw that it is used occasionally.

**Comment by shalva97** [comment]
hey, of course it will be used occasionally, but it is useless to leave it there. some will find that and think "oh wow, there  is a hidden element. it does nothing, haha, how careless they forgot to remove it"

**Comment by Milo123459** [comment]
Actually, good point, I'll make a PR that just "appends" it when needed.

**Comment by Milo123459** [comment]
Actually, you can't because it has to append it in a specific place

**Comment by PalmerAL** [comment]
I think the actual issue here is that it's possible to focus the button (by tabbing to it or clicking in the right spot) even when it has no text, which is probably how you noticed this. We should fix that by giving the button a `hidden` attribute when it's supposed to be hidden.

Other than that, there isn't any issue with having hidden elements in the DOM.

And the button is used sometimes, depending on the error. Example:
<img width="541" alt="Screen Shot 2021-02-06 at 6 51 39 PM" src="https://user-images.githubusercontent.com/10314059/107133294-60a4aa80-68ac-11eb-8871-e04ba3c6f972.png">
