### ISSUE TITLE
Back and Forward mouse buttons don't work

### ISSUE THREAD

**Issue by Shad0wSeven** [minbrowser/min#1501]
- **1.18.1**
- **macOS 11.0**

## Expected Behavior

When back and forward (side buttons) of mouse clicked, the browser should go back to the previous page, or go forward if possible respectively.

## Actual Behavior

Clicking back and forward (side buttons) of mouse, no behavior occurs.

## To Reproduce

Just use a mouse with back and forward buttons and they don't work.

**Comment by Syndamia** [comment]
It's probably because they aren't assigned in the `Keyboard Shortcuts` section in the [`Preferences`](min://settings) page. 

Forward and backward on the mouse are the exact same as pressing `Alt+Right` and `Alt+Left` respectively, so you just need to update the shortcuts (and restart the browser).
![image](https://user-images.githubusercontent.com/46843671/107879376-1c835c80-6ee1-11eb-98aa-104562058b9b.png)

**Comment by Shad0wSeven** [comment]
I use [Sensible Side Buttons](https://github.com/archagon/sensible-side-buttons) on macOS, which has the `cmd + [`, `cmd + ]`, so I guess I will remap
