### ISSUE TITLE
Open URLs from command line

### ISSUE THREAD

**Issue by mardukbp** [minbrowser/min#153]
It would be great if Min could be invoked with

`min http://my-favorite-site.com`

This is specially useful for integration with other programs like email readers.

**Comment by PalmerAL** [comment]
Fixed in facf72152968a709b484892b217dcbcb398be81f.

This actually fixes #84 for Linux as well, since this is how the default browser integration works on Linux.

**Comment by mardukbp** [comment]
Thank you very much! I spent several hours trying to fix this myself. Not being familiar with Electron, I did not succeed. But in the process I learned a lot about how `min` works. In my free time I will try to develop some features I miss and hopefully they will be useful as `min` plug-ins. I like the idea of having a snappy browser that consists of a thin layer on top of Electron. Then each user can add modules as (s)he sees fit. This is really a browser for power users. Thank you for your efforts!

**Comment by PalmerAL** [comment]
Glad to hear you like it!

**Comment by vidu171** [comment]
Hey,
I sometimes use a shortcut command to open slack and I prefer Min browser todo so. but the problem is when I already have an instance open It gives me the following error

`
$ min https://google.com
Gtk-Message: 22:48:08.759: GtkDialog mapped without a transient parent. This is discouraged.
`

It asks me to close any other instance of min that is already running

**Comment by PalmerAL** [comment]
@vidu171 That's issue #243.
