### ISSUE TITLE
calls in Slack.com doesnot work and if I close the tab its sound still continues

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1533]
- **Min Version:** 1.18.1
- **Operating system:** Arch 

## Expected Behavior
it should detect the request from Slack to enable Mic and I should hear other peoples sound.

## Actual Behavior

almost nothing works. Mic permission button doesnot appear, I cant hear their voice and sometimes calling sound doenot stop even if I close the tab. Im dont know how but that new tab should tell previous tab to stop call noise....
![image](https://user-images.githubusercontent.com/22417494/110940693-ba3b4180-8350-11eb-8405-90709bc8b773.png)

Im also getting this popup 
![image](https://user-images.githubusercontent.com/22417494/110940728-cb844e00-8350-11eb-9169-3b339c011a1f.png)

## To Reproduce
try to call someone on slack

**Comment by PalmerAL** [comment]
I tried this out on macOS, and I can reproduce the "did you start this call?" popup (which I think is due to issues with our popup window support), but everything else worked correctly, and I was able to send/receive video and audio. Closing the tab also worked correctly.

I think the next steps here are:
1. Try this out in a Linux VM, although I'm not sure if passing through the camera and mic even works there.
2. Make a Linux build for you to try that logs permission requests, so we can see if something strange is happening in your setup.

**Comment by shalva97** [comment]
thats weird, it never worked in my case....

> Try this out in a Linux VM, although I'm not sure if passing through the camera and mic even works there.
yea, why not. its gonna work, i have done that few years ago, it should also work today

> Make a Linux build for you to try that logs permission requests, so we can see if something strange is happening in your setup.
I will not mind...

**Comment by PalmerAL** [comment]
Can you go to these two test pages in Min: https://webrtc.github.io/samples/src/content/getusermedia/gum/ and https://webrtc.github.io/samples/src/content/getusermedia/volume/, and see if each one works (see if you get a permission prompt, and then check if you get camera/audio output).

**Comment by shalva97** [comment]
I get audio permission prompt but not camera, which is what I would expect since my desktop doesnot have one.

maybe tomorrow I will test this again, there was also other weird behavior that would hopefully happen again....

**Comment by PalmerAL** [comment]
Do Slack calls work for you in regular Chromium?

I was testing this in a VM yesterday (where microphone passthough was working but camera wasn't), and I was seeing similar behavior. It looked like Slack was requesting both microphone and camera access as a single permission request, which would fail due to the lack of a camera, and then nothing would work.

I assumed that you had a camera, and so what I was seeing was a different issue, but if you don't that could explain it...

**Comment by shalva97** [comment]
nice, there is progress...

currently I just tell others that Slack doesnot work for me and they blame it on my Arch Linux that nothing works on my dekstop, in a way they are correct, haha

**Comment by PalmerAL** [comment]
I think the next step to do here is test this in another Chromium browser. If it fails there as well, then I think we can close this as being caused by Slack requiring a camera to work. If it works there, then I'll investigate more.

**Comment by shalva97** [comment]
yeah, it also doesnot work in Chromium.... Slack bad, Minecraft good
