### ISSUE TITLE
Add feature "never save passwords for that domain" (Built in Pwd Mgr – Keychain)

### ISSUE THREAD

**Issue by blackgwe** [minbrowser/min#1549]
For some sensible pages (without 2FA) I never ever would save the password in `Min`. For that case I'd like to get an additional option: 
* `Save` (Button as it is now)
* `Don't Save`  (Button as it is now)
* `Never Save` or `Ignore domain.com` (Button or maybe a simple html link [ignore domain.com](ignore.domain.com) )

Unfortunately I do not have any knowledge with electron, but I think it could be implemented easily and add the check e.g. in `manager.getSuggestions(domain)`
https://github.com/minbrowser/min/blob/7b6eb996eebf752287df5f7dafe66671294ae80b/js/passwordManager/passwordCapture.js#L57-L65

**If it's to complicated, set this issue "won't fix"**

**Comment by PalmerAL** [comment]
This sounds reasonable to me.

**Comment by PalmerAL** [comment]
My plan here is to release an update this week, and then spend the next couple weeks working on this and some other improvements to the password manager.

**Comment by PalmerAL** [comment]
Fixed in 0f70d7d810bbaaca8e2a50b262ff964b24d58711.

Screenshot:
<img width="1363" alt="Screen Shot 2021-04-18 at 1 21 57 AM" src="https://user-images.githubusercontent.com/10314059/115136351-e186cd80-9fe4-11eb-892a-e92dc22447d0.png">

I sort of ran out of design ideas for the button - I wanted to separate it from the "don't save" button, but then it ends up floating off to the side and looking strange. But it's functional at least, and I suppose it doesn't look too terrible.

**Comment by PalmerAL** [comment]
Build: https://github.com/minbrowser/min/actions/runs/760150484
