### ISSUE TITLE
Can we hide the tab bar completly when in focus mode?

### ISSUE THREAD

**Issue by jkroso** [minbrowser/min#160]

**Comment by PalmerAL** [comment]
Any tabs other than the currently selected one are already hidden when in focus mode - do you mean hiding the current tab as well?

**Comment by jkroso** [comment]
Yea

**Comment by PalmerAL** [comment]
This is going to be difficult to do correctly, since Electron doesn't allow the title bar style to be changed after the window is created. I guess the titlebar could be hidden entirely, but this won't work very well on OS X:

<img width="1440" alt="screen shot 2016-05-22" src="https://cloud.githubusercontent.com/assets/10314059/15455086/6452da0c-200f-11e6-9bf9-06547b546b8b.png">

**Comment by pppov** [comment]
I would love this too, as I use Min mainly to connect to RuneAudio, and I only have one tab open all the time.
So removing the tab bar would be a nice option as it would save extra space...

**Comment by Milad-Laly** [comment]
This is possible with https://www.electronjs.org/docs/api/frameless-window I'll have to look into it.

**Comment by Milad-Laly** [comment]
The team has decided that it would cause UI issues and that it would be a hassle to implement
