### ISSUE TITLE
cant open downloaded image

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1641]
- **Min Version:** 1.19.2
- **Operating system:** Windows 10

## Expected Behavior
it should download image as .webp and photo viewer apps should open it

## Actual Behavior
it downloads as .jpg and cant be opened

## To Reproduce

try to download this image https://gloimg.gbtcdn.com/storage/item/6615272824267153408/16100/64a01624fcac.jpg_500x500.jpg 

it is .jpg but Edge downloads it as .webp and Photo app is able to open it and show

**Comment by lubiedo** [comment]
But the image is a JPEG. Why it should be downloaded with another extension or format?

**Comment by shalva97** [comment]
I mean cannot view it. have you tried to download it and open with photo viewer? it doesnot work for me

**Comment by PalmerAL** [comment]
This is fun... the URL has a .jpg file extension, but the file is actually a webp file. We assume that the extension is always right, and don't look at the actual content type of the file (and I'm not sure if Electron has a way to do that or not).

In the meantime, if you manually change the extension to `webp` after downloading, you should be able to open it.

**Comment by lubiedo** [comment]
@shalva97 Sorry, forgot to add the environment where I tested it:
* Min Version: 1.19.2
* Operating system: macOS Big Sur 11.4

![image](https://user-images.githubusercontent.com/63729414/121584544-c9cd3380-c9ee-11eb-81f3-d9fda1ab487d.png)

**Comment by lubiedo** [comment]
I tried to pay more attention to this issue and turns out that via Min the response headers specify the file as `content-type: image/webp` and via others (ie. curl) `content-type: image/jpeg`.

@PalmerAL Question is: should we believe the file in the URL or modify it and append an extension belonging to the content type? Personally I think that the extension specified in the URL should remain as is and avoid creating future inconveniences.

**Comment by PalmerAL** [comment]
I think the "right" thing to do would be to use the content-type header, since this is what other browsers do when downloading. However, AFAICT, Electron doesn't have an easy way to get the content-type of the image. I think you'd have to add a webRequest listener and store the content types in a cache somewhere, but that's going to be annoying to do and introduce a bit of performance overhead. And it should be pretty rare for this to happen, since most sites use the correct file extension.

So I'm fine with closing this and leaving the extension as-is.

**Comment by lubiedo** [comment]
Just tested with Safari and Content-Type was `image/jpeg`. I'm wondering why Akamai CDN is saying it is an `image/webp`. Modified the user-agent to be `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77` and the content type was the correct one.

I'm OK with closing it too.

**Comment by PalmerAL** [comment]
Chrome was (or maybe still is?) the only browser to support webp, so they’re sending a jpeg to anything else. Regarding the second part, they might be looking at the `accept` request header as well.

Marking this as wontfix.
