### ISSUE TITLE
Content blocking issue on https://www.coolmathgames.com/

### ISSUE THREAD

**Issue by coolprofessor** [minbrowser/min#1705]
Site doesn't work with ad blocking on.

**Comment by PalmerAL** [comment]
Thanks for reporting. In general, these issues tend to be difficult to fix, because it's easy for the site to detect when ads aren't loaded. Sometimes, you can write a special JS file that gets inserted into the site to make it work, but that tends to break fairy easily.

I looked at what uBlock is doing, and that's the approach they're taking:

https://github.com/uBlockOrigin/uAssets/blob/54014d80660fc6c06ef5c4cafd718d4e4985aaec/filters/filters.txt#L11726-L11733

So you could make a userscript for this in Min (https://github.com/minbrowser/min/wiki/userscripts):
```
// ==UserScript==
// @name Example Script
// @match coolmathgames.com
// @run-at document-start
// ==/UserScript==

window.cmgpbjs = false;
window.displayAdblockOverlay = false;
window.google = false;
```

That seems to work for now, but it'll probably stop working in the future.

**Comment by coolprofessor** [comment]
Thanks!!!
(sorry for the late response)
