### ISSUE TITLE
For RPi OS

### ISSUE THREAD

**Issue by pranavr2003** [minbrowser/min#1797]
It would be great if a version was created specific for RPi-OS (32-bit version). Are there plans for an armhf release out-of-the-box?

I love it on Windows, would love it on the Pi too, which is reserved for non-entertainment/meetings stuff (I would love to be able to StackOverflow into it on the armhf PiOS without having to build it specifically)

**Comment by Syndamia** [comment]
> Are there plans for an armhf release out-of-the-box?

armhf support really isn't being worked on right now. According to #1374, Min actually supported armhf until version 1.17, so since around December of 2020 it has stopped working.

> RPi-OS (32-bit version)

Excluding the fact that we don't currently support the OS, Chromium, one of the main things Min is based on, dropped support for 32-bit systems a while ago (https://github.com/minbrowser/min/issues/1369#issuecomment-917780145), so that is most probably impossible to do solely on our end.
