### ISSUE TITLE
Additional padding in browser navbar

### ISSUE THREAD

**Issue by matheusAMDS** [minbrowser/min#1823]
- **Min Version:** 1.22.1
- **Operating system:** Fedora 35 + i3wm

## Expected Behavior
Looking through the screenshots available, it shoudn't have such a big top padding in navbar
## Actual Behavior
![Captura de tela de 2021-12-12 15-07-14](https://user-images.githubusercontent.com/39417098/145724163-f0eb7a5b-4c36-4178-8af5-4912e62cde69.png)

## To Reproduce
Just install the browser normally

**Comment by PalmerAL** [comment]
The space at the top exists so there's a way to drag the window - due to limitations in Electron, it's not possible to have the tab bar be draggable and still make it possible to click on the tabs. There's been some discussion in the past about coming up with a better design for this: #630, but nothing was ever decided.
