### ISSUE TITLE
Bangs need twice ENTER press

### ISSUE THREAD

**Issue by objectprogr** [minbrowser/min#1908]
Hi, 
When I use my own defined bangs, I have to press enter twice.
Why? And how to change it?

**Comment by PalmerAL** [comment]
Oh, that's a good point. The reason is to provide an opportunity to enter a search query, since the bang can have a search parameter (like `https://example.com/?q=%s`). But I've changed the behavior in 71dbe78ff00f7cec3fdb26252bafd4032c9c0383 so that it only does this if there actually is a search parameter in the URL.
