### ISSUE TITLE
[Question] Have You Considered Basing Min on UnGoogled Chromium?

### ISSUE THREAD

**Issue by arandorion** [minbrowser/min#1922]
I like Min, but I can't get past the fact it's based on Chromium. Both Brave and UnGoogled Chromium are working to ungoogle Chromium as much as possible, and they are mutually sharing their updates. Brave keeps a detailed list of all of the ungoogling changes, and it's a lot.

Have you considered using UnGoogled Chromium as the basis for Min? Or even just importing specific ungoogling changes that both Brave and UnGoogled Chromium have adopted?

Thanks

**Comment by rewkha** [comment]
this is an electron app, it is based on the framework that is using chromium as a basis. I think it it a question not to the min browser developers

**Comment by PalmerAL** [comment]
Oops, I thought I wrote a response to this before, but apparently I didn't, sorry.

Electron and ungoogled Chromium aren't comparable. Chromium consists of two parts: the Chromium rendering engine, and then the "browser" part, which is a UI and a bunch of Google services added on top of that. Electron takes just the rendering engine and adds support for accessing operating system APIs on top, which lets us make a custom user interface and also render webpages. Ungoogled Chromium  is taking the entire browser, and removing the Google service integration (plus some other things they list here: https://github.com/Eloston/ungoogled-chromium#enhancing-features).

So first, Electron doesn't have most of the Google integrations that ungoogled Chromium is trying to remove. (I would say "all", but I haven't done a detailed audit to verify this is the case). And also, since ungoogled Chromium doesn't offer comparable features, there's no simple way to replace Electron with it.

**Comment by arandorion** [comment]
Thanks for the info. Sounds like Min doesn't have the Google stuff either (or at least most of it). That's cool.

Thanks
