### ISSUE TITLE
Manifest V3 is Google's attempt to break adblock. Is min affected?

### ISSUE THREAD

**Issue by ducheng0** [minbrowser/min#1953]
https://www.neowin.net/news/the-eff-will-fight-google-chrome-manifest-v3-which-kills-extensions-that-reliably-block-ads/

ManifestV3, the next major revision of Chrome's APIs severely limits what extensions can do... and it makes AdBlock obsolete on Chrome.
I'm just wondering, is Min affected since it's based on Chromium, and if yes, what will we do to restore ad blocking?

**Comment by PalmerAL** [comment]
Not sure if you found the answer to this already, but the answer is basically no: https://github.com/electron/electron/issues/17602#issuecomment-497412179
That comment is old at this point, but I haven't seen anything since that would indicate the webRequest APIs we use in Electron will be changing.
