### ISSUE TITLE
Help | Build for Debian from Windows

### ISSUE THREAD

**Issue by dramaticrobotic** [minbrowser/min#2146]
How do I build a Debian package from windows?

**Comment by PalmerAL** [comment]
I'm not sure to be honest, what happens when you try to run the command?

In general, cross-compilation doesn't work very well - is it possible for you to build the package on a Linux machine? You could also use Github Actions, which is how I build the official releases: https://github.com/minbrowser/min/blob/master/.github/workflows/build-packages.yml

**Comment by dramaticrobotic** [comment]
I've tried both Mac os building and Linux building, and neither of them works. It gives the unknown argument error "packageName" which is apparently a problem with the package.json.

**Comment by dramaticrobotic** [comment]
I've successfully built Linux packages with GitHub actions. It seems that the GitHub environment has NPM configured correctly.
