### ISSUE TITLE
Opening the google applications dashboard from GMail opens another page

### ISSUE THREAD

**Issue by cbertelli** [minbrowser/min#2256]
- 1.28.0-beta
- macOS 10.14

## Expected Behavior

I call this widget

• • •
• • •
• • •

a dashboard icon. It should should open a box with google apps

## Actual Behavior

… but it goes elsewhere

## To Reproduce

Just click on the widget. Really weird.

**Comment by PalmerAL** [comment]
This seems to be caused by the script we inject on Gmail to override the user agent. I can't figure out why; the JS that causes this is heavily obfuscated. However, if I remove the script, the problem it originally solved doesn't appear to happen any more. Not a very satisfying solution, but it works.

Thanks for reporting!
