### ISSUE TITLE
min 1.28-beta does not work on windows 7 (Discardvirtualmemory process error (missing from kernel 32.dll library)

### ISSUE THREAD

**Issue by marioseixas** [minbrowser/min#2257]
I'm using windows 7 i get an error saying the entry point is not found for the process "discardvirtualmemory within the Kernal32.dll library.

![error](https://github.com/minbrowser/min/assets/9296780/b69340a7-c156-4fd8-b933-8d9860578a7f)

**Comment by PalmerAL** [comment]
Chromium/Electron no longer supports Windows 7 and 8 ([blog post](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice)), so it won't be possible for this to work. However, we should document this and provide links to the last-working version, which will be the current release.

Actually, I would probably recommend switching to Firefox for as long as they still support windows 7, since it's best to continue getting security updates with an updated browser engine.

**Comment by VolkanSah** [comment]
Upgrade your System! Or use older version of your program!
