### ISSUE TITLE
Min.app doesn't open

### ISSUE THREAD

**Issue by 0xIgnacio** [minbrowser/min#2346]
I tried to open the app as soon as I installed it using `brew install --cask min` and MacOS sends the following message:

> "Min.app" can't be opened because Apple cannot check it for malicious software. 
> This software needs to be updated. Contact the developer for more information. 
> Homebrew Cask downloaded this file.

Apple help says this:

> Note: You can also grant an exception for a blocked app by clicking the Open Anyway button in Privacy & Security settings. This button is available for about an hour after you try to open the app.

After this I tried to install the app through the zip on [minbrowser](https://minbrowser.org/) but it still doesn't work.

**Comment by PalmerAL** [comment]
Try right-click > "open" > "open anyway".

**Comment by 0xIgnacio** [comment]
I followed the steps that were told to me in Apple Help and I was able to use the browser. The feedback was so that you would be aware of the error in case you want to take action about it. Anyway, thank you very much, I love your browser.

**Comment by Kepler-69c** [comment]
The error message appears because the Min Browser is not signed. To sign an application, you need to join the Apple Developer Program, which costs ≈$100/year.
When downloading from the [website] (https://minbrowser.org), the steps to open the application are mentioned, but when installing with brew, of course, this message does not appear. I would therefore not really consider it a mistake on Min's part.
