### ISSUE TITLE
Default DuckDuckGo search engine returns no results if "Block Scripts" is checked

### ISSUE THREAD

**Issue by acidus99** [minbrowser/min#2382]
- **Min Version:  1.31.1 (1.31.1)**
- **Operating system: macOS 14.2.1**

Min's default search engine is DuckDuckGo. DuckDuckGo appears to require JavaScript. If you use Min with "Block Scripts" checked, it returns no search results, as shown in the video below:

![min](https://github.com/minbrowser/min/assets/4118560/f5e7715e-1b58-443e-a11b-d11369ad30b5)

## Expected Behavior
When "Block Scripts" is checked, the default search provider (DuckDuckGo) should return results.

## Actual Behavior
When "Block Scripts" is checked, the default search provider (DuckDuckGo) does not return results, as shown in the video above. The develop

## To Reproduce

- Configure DuckDuckGo as your search engine for Min
- Check "Block Scripts"
- Type a search term into the URL bar and hit enter
- No search results are shown as seen in the picture below (which shows the default version of DDG requires JS)

<img width="1265" alt="image" src="https://github.com/minbrowser/min/assets/4118560/549a8cf1-168f-42a5-b515-d39d9e2a2a9d">

## Suggestions

DuckDuckGo does have an non-JavaScript version available at:

https://html.duckduckgo.com/html/

You can work around this issue configuring a Custom search engine and using the config URL:

https://html.duckduckgo.com/html/?q=%s

You can see that working in the video below:

Please consider these options:
* Add a "DuckDuckGo (NO JS)" option to the list of built in search engines
* Use the non-JS version of DuckDuckGo (and other search engines) automatically, based on the value of the "Disable Scripts" checkbox

**Comment by PalmerAL** [comment]
> Use the non-JS version of DuckDuckGo (and other search engines) automatically, based on the value of the "Disable Scripts" checkbox

Oh I like this idea!

<hr>

A bit off topic, but do you find this setting useful? I've been wondering if anyone actually uses it; extensions like noscript let you make exceptions so that you can get important sites to work, but we just have a global on/off switch. Is the browser still usable for you with this setting applying to every site?

**Comment by acidus99** [comment]
I do like it, but I only just started using Min.

**Comment by acidus99** [comment]
BTW I checked the included search engines to see what worked with "Block Scripts" checked:
* Google - Works
* Bing - Works
* Yahoo - Works
* Baidu - Work
* Startpage - Returns results, but logo and top banner is missing
* Ecosia - Works
* Qwant - Works
* Wikipedia - Works
* Yandex - Works

**Comment by PalmerAL** [comment]
I looked into this, and this turned out to be because we were filtering scripts at the network level, which wasn't blocking inline scripts or allowing `<noscript>` tags to run.

I have a fix for this here: https://github.com/minbrowser/min/tree/better-js-filtering

As a consequence, DDG will now detect when JS is disabled and redirect to the HTML site.

Would you be willing to test the branch above? Following these instructions: https://github.com/minbrowser/min/tree/better-js-filtering, but with a `git checkout better-js-filtering` beforehand.
