### ISSUE TITLE
Title Bar is not hidden on Elementary OS Freya

### ISSUE THREAD

**Issue by artillect** [minbrowser/min#242]
I installed Min on my installation of Elementary OS Freya and was disappointed to see that the title bar did not hide, and the window buttons were not combined into the top bar in Min.

**Comment by PalmerAL** [comment]
I'm not sure what the best way to do this is, since there needs to be room for the menu bar. Midori has a dropdown menu instead of a menu bar, but this wouldn't work well on other operating systems.

In Min 1.5, you can press alt to hide the menu bar, which would help to reduce the height of the title bar:

<img width="638" alt="screen shot 2016-08-28" src="https://cloud.githubusercontent.com/assets/10314059/18036365/3a6f5af0-6d2e-11e6-836f-a310c7e1cb9d.png">

**Comment by Artillect** [comment]
That does help a bit, but still doesn't have the same effect that it does on OS X.

**Comment by Overtorment** [comment]
Yep, totally spoils the experience

**Comment by Overtorment** [comment]
Toyed around, `frame: false,` in `new BrowserWindow`  fixes that, but screws the controls of the browser.

**Comment by PalmerAL** [comment]
This is fixed in the latest release.
