### ISSUE TITLE
Insert visual indication of bookmark

### ISSUE THREAD

**Issue by MauroLima-hub** [minbrowser/min#2423]
It would be nice to have some VISUAL INDICATION that I already have bookmarked some page.
Maybe a star or something like that!
Better yet if it could diferentiate if I am at the root PARENT page or some DESCENDANT of them!
This way, if I em on any course/page inside https://www.geeksforgeeks.org/ for example
I would see that I have bookmarked the ROOT page of this site, and will not add children bookmarks, unless I want, of course!

Still in this path, MAYBE we could see, pointing to PARENT adress, the CHILDREN adresses that I bookmarked, so I could easyly see what I market to read/staudy on their adress. A click/expand tree, with clickable branches kind of thing.

It would help navigate EASIER on MY BOOKMARKS on that site!

I'm on my first steps on Odin Project. Thanks for the browser.
I really would like to code my own, and this is preety much que QUALITY I would like to achieve!

**Comment by PalmerAL** [comment]
There is a star: 
![Screenshot 2024-04-12 at 1 44 43 PM](https://github.com/minbrowser/min/assets/10314059/91103d33-f02f-4320-b18d-15442cb368f9)

The idea of showing what other pages on a site are bookmarked is interesting. However, in most cases, I think it does make sense to have separate bookmarks for the root page and a sub-page (because the subpage has most of the specific information you want).
