### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by PandawanFr** [minbrowser/min#246]
Hey! 

Really like the app (I know I already said that in a past post but whatevs).

Anyways, do you think it would be possible for you to implement a Dark Mode? It would be awesome since I am using Mac OS's Dark Mode... 

Thanks!

**Comment by PalmerAL** [comment]
Electron has a <a href="http://electron.atom.io/docs/api/system-preferences/#systempreferencesisdarkmode-macos"> systemPreferences.isDarkMode </a> API, so this shouldn't be too difficult to implement.

What should the dark mode look like? Currently, the tab colors are adjusted to be darker late at night, so I guess the same thing could happen when dark mode is enabled. The only part of the UI that isn't affected by this is the task overlay, so that would need a special dark theme.

**Comment by PandawanFr** [comment]
Well, you could make a dark mode for the task, and the settings. 

I guess just a basic dark mode like most web apps do would be pretty good

Look at [Twitter's Dark Mode ](https://i.kinja-img.com/gawker-media/image/upload/s--HnjLGR6Z--/c_scale,fl_progressive,q_80,w_800/vzfwi4epygjhtu8mia8v.png)

or perhaps [Sublime Text's Dark Mode ](http://cache.filehippo.com/img/ex/2794__Sublime_text_2_1.png)

**Comment by PandawanFr** [comment]
How about somewhat [like that?](https://gyazo.com/9ac28f341aad310801cf62b6ee078a6a) 

PS: Just an idea, you don't have to make it like that if you don't like it.

**Comment by PalmerAL** [comment]
Looks nice!

**Comment by PandawanFr** [comment]
Do you want me to make a pull request? Or do you want to make your own?
(I don't really care tbh, do whatever you want)

**Comment by PandawanFr** [comment]
Tried making one here: https://github.com/minbrowser/min/pull/247
btw, I added the checkbox in the preferences, but didn't know how to link it to the other pages, so... Right now, all pages are forced in DarkMode, what you have to do is remove them, and add the stylesheet to the head whenever it's enabled.

**Comment by PandawanFr** [comment]
ok, pull request is done #247
