### ISSUE TITLE
start Min in a specific zoom mode

### ISSUE THREAD

**Issue by pppov** [minbrowser/min#259]
Is it possible to start Min in a specific zoom mode? Like 1.2 or 0.8?

Now I always set it to the zoom I want, after I start it, but it is always the same, so it would be nice to set it in a configuration file. (In Midori I know how to do this, but not in Min...)

**Comment by PalmerAL** [comment]
Is the specific zoom for one particular website? I'm wondering if there should be a global zoom setting, or if Min should just remember the last zoom level for each website (like what Firefox does).

In the meantime, if you want to build Min yourself, you could add this to the top of ```js/webview/zoom.js``` as a workaround:

```
electron.webFrame.setZoomFactor(1.2)
```

**Comment by pppov** [comment]
Remembering the zoom setting for each website would be best for most users, I guess.
For my purposes remembering the last zoom setting before I close it, would work too. 

Doesn't Min remember other setting while closing, like window dimensions? Wouldn't there be a way to remember the zoom setting as well? (I know nothing about coding, so consider me a fool for asking...)

(I also see now in your screen shots that the task menu (the three lines) is on top of the window. In my Min (Ubuntu 14.04 Unity), it is on the tab bar, which takes up extra space. But maybe this is something for another thread...)
![schermafdruk van 2016-10-11 09 48 22](https://cloud.githubusercontent.com/assets/18084725/19262568/001b1678-8f98-11e6-918f-e1dfdbcb941d.png)

**Comment by PalmerAL** [comment]
> Doesn't Min remember other setting while closing, like window dimensions? Wouldn't there be a way to remember the zoom setting as well? (I know nothing about coding, so consider me a fool for asking...)

That would be possible, but I think it's probably better to save it whenever the zoom level on a website is changed. That way, instead of just remembering the last zoom level, something like this could be saved:

```
{
    'example.com': 1,
    'example2.com': 1.1,
    'example3.com': 0.8
}
```

That way, you could have multiple custom zoom levels for different sites.

>(I also see now in your screen shots that the task menu (the three lines) is on top of the window. In my Min (Ubuntu 14.04 Unity), it is on the tab bar, which takes up extra space. But maybe this is something for another thread...)

On OS X, the window controls and the tab bar are combined, so the button is still in the tab bar, it just looks different because there are no window controls above it.

<img src="https://minbrowser.github.io/min/splash/searchbar.png"/>

This would look a lot better if the controls were combined on Ubuntu as well, but there's no built in way to do this in Electron on operating systems other than OS X.

**Comment by pppov** [comment]
Well, that's one point for OS X then. It looks a lot nicer. I'll take it up with the Ubuntu people if they can or intend to do something like that as well.
Thanks for your replies

**Comment by Sestowner** [comment]
I think this can be closed.
