### ISSUE TITLE
Two-finger swipe on Linux is too sensitive

### ISSUE THREAD

**Issue by 5nefarious** [minbrowser/min#264]
It is virtually impossible to scroll with two fingers without accidentally navigating forward/backward. This makes the browser almost unusable with a touchpad.
I saw that there's an issue open here to completely disable two-finger swipe navigation: https://github.com/minbrowser/min/issues/39
However, I think the sensitivity should also be reduced to make the feature usable.

**Comment by PalmerAL** [comment]
The current code just tracks the amount of vertical movement in a 4-second interval. Instead, it should probably check if the amount of vertical movement is above a minimum, and if the amount of vertical movement divided by the amount of horizontal movement is above a minimum as well.

**Comment by PalmerAL** [comment]
I've started working on redesigning the gestures in the <a href="https://github.com/minbrowser/min/tree/swipe-gestures">swipe-gestures</a> branch. Can you try that and see if it has the right sensitivity level?

**Comment by inefarius** [comment]
This is definitely an improvement. However, I am noticing that the if you scroll and then move your fingers slightly left or right at the end it still registers as a command to go forward or backward. Should there be some safeguard against that?

**Comment by inefarius** [comment]
I am thinking that once the browser registers a scroll, that action should be locked in so it cannot also interpretted as a swipe.

**Comment by PalmerAL** [comment]
I've improved this in dd2b02fe68ce88f68e550a7e6bd9bb1282909643.

Previously, if the page was scrolled to the edge at the end of the swipe, and the distance of the swipe was more than a certain amount, the gesture would be counted as a swipe. Now, the part of the gesture that is counted as a scroll is not counted as a swipe. This means that if you swipe really quickly, you can still navigate back instead of scrolling all the way to the edge of the page, but most scrolls shouldn't count as swipe gestures.

Can you try this and see if it works?

**Comment by PalmerAL** [comment]
This has been merged in #284.

**Comment by PalmerAL** [comment]
The swipe gestures have changed significantly since this issue was created, and I believe this is fixed now; please open a new issue if you're still having problems with it.
