### ISSUE TITLE
Some pages are not loading correctly

### ISSUE THREAD

**Issue by satyaog** [minbrowser/min#283]
On Linux KDE Neon 5.8.4 using Min 1.5.0, https://bitbucket.org/account/signin/ and https://bitbucket.org/account/signup/ are not loading correctly. They were loading correctly before yesterday. I tried refresh, closing the page, closing the browser, removing Min and deleting /home/${USER}/.config/Min. https://bitbucket.org/ seams to work well tho.

Anything I can do to give more info? Maybe a clean /home/${USER}/.config/Min?

Thank you,

![image](https://cloud.githubusercontent.com/assets/6757005/21148345/de75530c-c125-11e6-8b51-54a23f5fe26c.png)

![image](https://cloud.githubusercontent.com/assets/6757005/21148333/d4f3398e-c125-11e6-9930-75c8016b0e39.png)

**Comment by PalmerAL** [comment]
This is happening because of a bug in Chromium 53 (https://bugs.chromium.org/p/chromium/issues/detail?id=664177), where Chromium incorrectly rejects some TLS certificates if the version of chromium is more than 10 weeks old. Bitbucket is hosting the resources for their signup page on a separate domain that has one of the affected certificates, so the page won't load completely if your computer clock is set after December 10th (10 weeks from when the version of Electron was built).

This has been fixed in the latest version of Electron (http://electron.atom.io/blog/2016/12/09/certificate-transparency-fix). Given the number of sites that are broken because of this, it probably makes sense to release a 1.5.1 version of Min with electron 1.4.12.

**Comment by satyaog** [comment]
@PalmerAL Thanks a lot for your answer and your work. It's a great browser.

I'll wait patiently for a new release.

**Comment by PalmerAL** [comment]
1.5.1 has been released; you can download it from here: https://github.com/minbrowser/min/releases/tag/v1.5.1.

**Comment by satyaog** [comment]
Waw that was fast! Thanks a lot again! Works flawlessly
