### ISSUE TITLE
Create snap package and publish it to Ubuntu Store

### ISSUE THREAD

**Issue by dfiloni** [minbrowser/min#294]
Hi,
thank you for the great work!
I created a repository to build min as snap package (http://snapcraft.io/), it works fine (tested on Ubuntu xenial) except for system wide theme which is not recognized (for example in Save Page As dialog) and it runs in strict confinement.
You can find the snap code here: https://github.com/dfiloni/min-snap
Could you publish min to Ubuntu Store? http://snapcraft.io/docs/build-snaps/publish

Thank you!

**Comment by PalmerAL** [comment]
Thanks for doing this! I should have time to try this out in a couple of days.

**Comment by brunobord** [comment]
It's been months, now. Shouldn't the snap package be available already? I think it'd help growing the user base if you could provide your binaries via a trusted package manager (snaps, debian packages via a PPA, etc).

**Comment by PalmerAL** [comment]
Oh, I completely forgot about this! I'll try to finish it soon.

**Comment by eaglersdeveloper** [comment]
Already year has passed. Did you forget again?

**Comment by PalmerAL** [comment]
I haven't forgotten, it just hasn't been a priority. Since this issue was created, there's now a module to build snaps for Electron: https://github.com/electron-userland/electron-installer-snap, which might be a bit easier than manually building it (although that might work as well). If you're interested in working on this, you're welcome to submit a PR for it.

**Comment by Syndamia** [comment]
The snap code that OP provided is severly out of date and talk about Linux packages is more serious in #735.
