### ISSUE TITLE
Reader view shows black text on dark background at night

### ISSUE THREAD

**Issue by 5nefarious** [minbrowser/min#295]
I've noticed that min changes the background to dark at night. While I like this feature, it seems that the text in reader view stays black even when the background is dark.

OS: Linux
Min Version: 1.5.1-1

**Comment by dbfreem** [comment]
I verified this is the same on windows. Supprised others haven't reported this.

**Comment by PalmerAL** [comment]
I think there's two separate issues here:

1. What the original issue was likely about was that if you opened an article while the browser was using the light theme (like if you opened an article at 9:59 PM), and then the browser switched to dark theme, the text would stay black. This should be fixed in 1.10, because the theme will no longer change after the article has loaded (so you have to reload it for the theme to switch to dark).
2. While the article is still loading, the theme won't be set inside the `iframe`, so you'll see black-on-black until the article finishes loading. Depending on the speed of your internet connection (and the speed of the site you're opening), this could be several seconds, which might be what you're noticing.

**Comment by dbfreem** [comment]
I am seeing this behavior still in v1.10.1. The current time is 11:08PM, I did open the browser for the first time before 10pm.

![image](https://user-images.githubusercontent.com/9778569/62508496-d6bae380-b7d5-11e9-8d98-ab9e27701704.png)

**Comment by manoger** [comment]
The problem continues for sites, like "Unity Documentation" and "Quora".

**Comment by PalmerAL** [comment]
@manoger If this isn't just in reader mode, it's probably #954.

**Comment by manoger** [comment]
so, it will be fixed in a future version? great!

**Comment by PalmerAL** [comment]
@manoger That issue should have been fixed in 1.14, are you still seeing it after updating?

**Comment by manoger** [comment]
oh, I'll update. Thanks @PalmerAL :D
I appreciate this browser a lot.

**Comment by Sestowner** [comment]
I think this can be closed.
