### ISSUE TITLE
pdf 

### ISSUE THREAD

**Issue by xicys** [minbrowser/min#308]
When accessing a pdf, multiple tabs (5) are opened showing that file

**Comment by PalmerAL** [comment]
Is there a specific site this happens on? I think I've seen this happen before, but I can't reproduce it by entering a PDF URL in the seach bar or by clicking on a link.

**Comment by xicys** [comment]
It does not happen by entering a specific PDF URL for me, but by clicking on a link to a PDF. Any Google [PDF] result does it for me

**Comment by PalmerAL** [comment]
I can't reproduce this by clicking on a Google search result link, by cmd+clicking to open in a new tab, or by opening the link from the context menu. Can you share the URL for a search that does this?

**Comment by abejfehr** [comment]
This happens from time to time with Google search results. I've seen it happen where it opens duplicate tabs, but I can't find a test case for that right now.

I did however, find this one, which is almost as good:

1. Command + Click [this link](https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=0ahUKEwiuyfq7rfTRAhXC24MKHVKPCQYQFgglMAI&url=http%3A%2F%2Fwww.doe.mass.edu%2Fframeworks%2Fmath%2F0311.pdf&usg=AFQjCNEM48XmNEdG2GPCqynBnMMc5G7EzA&sig2=sNMwqzVKI3nODesNfNqODQ&bvm=bv.146094739,d.amc&cad=rja)
2. Observe that two tabs are opened, one with the pdf and the other is blank

**Comment by PalmerAL** [comment]
@abejfehr Fixed in 5e5aeddad986f72cd1edc3033ce595ad88850974.

The problem was that the original code was deciding which tab to open the PDF file in based on the URL. Since this URL was the Google redirect URL, rather than the actual file, it was creating a new tab instead, and leaving the tab with the Google URL open.

@xicys Could you see if this fixes your issue as well?

**Comment by xicys** [comment]
Yes it does. Thank you very much
