### ISSUE TITLE
[Request] Builds with removed inspector

### ISSUE THREAD

**Issue by Corsten56** [minbrowser/min#310]
Hello.

Thanks. Good browser. Very fast and looks promising.

I've a suggestion - how about builds without "inspector" functionality? It should be faster and require less memory.

Best regards.

**Comment by PalmerAL** [comment]
I'm not sure removing the inspector would have much impact on speed or memory usage. The inspector code doesn't run until you open it, so unless you are using the inspector it shouldn't have any impact. Also, that would probably require a custom build of Chromium, rather than just using the builds provided by Electron.
