### ISSUE TITLE
Unable to capitalize first letter of search

### ISSUE THREAD

**Issue by abejfehr** [minbrowser/min#314]
This probably doesn't actually matter, as I'm sure it doesn't affect the results given in most search engines, but I found it very strange that I was unable to type "SHARCNET" as a query after opening a new tab.

To reproduce:

1. Open the browser to a new task or tab
2. Try typing "SHARCNET"
3. Observe that "sHARCNET" gets typed instead, and it is impossible to capitalize the first letter directly

**Comment by PalmerAL** [comment]
The reason for this is that autocomplete ignores capitalization, and when a website is autocompleted, the autocomplete result replaces whatever you typed in the searchbar. So if you type "G", it will autocomplete to "github.com", and the lowercase form will be used. In your case, you've previously visited a website whose domain name starts with "s", and the autocomplete suggestion for that domain is replacing the capital S with a lowercase s.

It would be easy to just keep the capitalization of whatever you typed and add the rest of the autocomplete onto the end, but I'm not sure that's the correct behavior either, because path names are case-sensitive. If you type "github.com/T", and you've previously visited "github.com/trending", "github.com/Trending" shouldn't autocomplete because "github.com/Trending" and "github.com/trending" are two different webpages.

**Comment by abejfehr** [comment]
Google Chrome preserves the case of what you've typed in the bar, and whenever something you've typed matches an autocomplete entry case insensitively, when you hit enter it's replaced with whatever case is in the autocomplete. If there is no autocomplete entry, the case you typed is used.

I think that would be pretty reasonable behaviour to have here, too.

**Comment by z3t0** [comment]
I dont have this issue?

**Comment by abejfehr** [comment]
@z3t0 it only would happen if you've already visited a site that starts with 's', if you're trying to reproduce the case I wrote in my issue.

In your case, since you've already been to github (I assume), try searching for something in all-caps that starts with 'G', like 'GRASS'.

**Comment by z3t0** [comment]
Okay got it!

**Comment by PalmerAL** [comment]
Finally fixed (3 years later!) to match the behavior described in comment#2 in 96b721a188941ec3c362a84561121d289015f2aa.
