### ISSUE TITLE
Feature Request: Touch Bar Support

### ISSUE THREAD

**Issue by dockleryxk** [minbrowser/min#335]
Is there any interest in touchbar support? I know Electron [supports it](https://github.com/electron/electron/blob/master/docs/api/touch-bar.md). I might fork and add it in myself if it fits in.

Either way thanks for this cool browser!

**Comment by PalmerAL** [comment]
Touchbar support would definitely be useful!

What would be most useful to have in the touchbar? Back/forward buttons? Recent/most visited bookmarks? Currently open tabs? Tasks?

**Comment by dockleryxk** [comment]
If you're willing, I think the choice between basic controls such as new tab, new private tab, back, forward, and stop/reload and a tab listing would be best. If not, I think the tab idea is most useful and provides a nice contrast to what many browsers are doing.

**Comment by dockleryxk** [comment]
Ahh, yikes. Seems to be only in the (beta release)[https://electron.atom.io/blog/2017/03/08/touch-bar-support]. I've forked minbrowser and will take a preliminary stab at this. I'll report back here when I'm done.

**Comment by PalmerAL** [comment]
Does Electron have a way to integrate with the built-in touch bar customization UI (http://www.laptopmag.com/images/wp/purch-api/incontent/2016/11/ctb_05-640x400.png)? If so, it's fine to add options, but if not its probably not worth adding a separate UI for this.

Either way, it might be best to just show back/forward, current tabs, and a new tab button as the default set. There isn't a lot of room in the touchbar, and it seems like it would get cramped otherwise (although I don't have a touchbar Mac, so it's hard to tell if this is the case or not). 

Using beta releases of Electron should be fine, since there usually pretty stable (and there will probably be a stable release of Electron by the time this is released anyway).

Thanks for doing this!
