### ISSUE TITLE
How do you make it battery efficient

### ISSUE THREAD

**Issue by z3t0** [minbrowser/min#337]
Hi! 

In trying to learn more about electron and was surprised to read that this app is very fast, efficient and built on electron. Compared to other apps like 
Atom which is not so efficient, how did this app manage to be efficient.

**Comment by PalmerAL** [comment]
There isn't really one single thing that makes Min efficient. Ultimately, it's just taking each piece of code, looking at every operation it does, and figuring out if those operations actually have to be done. the more code there is, and the more things it does, the slower the app will be. Not using a framework also helps a lot, since the DOM can be directly updated instead of going through the framework.

The downside of doing this is that it makes it much more difficult to add new features, and can make the code less readable. Depending on what your priorities are, it may make sense to use a framework even though the app won't be quite as fast.

For the most part, optimizing for Electron is the same as optimizing for a browser. The only Electron-specific thing to be careful with is sending IPC's between processes, particularly using the ```remote``` module. Asynchronous IPC's won't stop the rest of the app from running, but if they have to be sent to display the results of user input, they can still make your app feel slower. The ```remote``` module uses IPC's to access the main process, and because it is synchronous, the entire app will stop until the IPC has ben sent to the main process and another IPC sent in return. It's best to do this as little as possible, but in most apps it won't be an issue.

**Comment by z3t0** [comment]
Thanks! I'll try it out and see how it is

**Comment by z3t0** [comment]
Hmm okay I'm a little bit confused now. Min runs on electron, electron is mostly a chrome browser? So how would min be any faster / more efficient than chrome

**Comment by z3t0** [comment]
This is amazing...

**Comment by PalmerAL** [comment]
The actual renderering of web content is the same as Chrome, so the speed and power usage of that should be the same. The main difference is in the UI. It's hard to say for sure if Min is actually faster than Chrome or not, because there's not a good way to measure exactly how much CPU time Chrome uses. Anecdotally, the Min UI seems to run as fast or faster than Chrome (and the UI in Min is mostly single-threaded, so speed correlates pretty well with efficiency / power usage). The battery life in Min also seems much better than Firefox (which I used previously), although a lot of that is likely due to Chromium rather than anything specific to Min.

I did attempt to get some measurements of Chrome's power usage using <a href="https://software.intel.com/en-us/articles/intel-power-gadget-20">Intel Power Gadget</a>. Opening a tab, the power usage in Min (using an i5-5257U) goes from around 1 watt when idle to 2 watts when opening a tab, whereas in Chrome it jumps to around 5 watts. Typing in the searchbar, I get around 3 watts in Chrome, and around 3.5 watts in Min. Loading pages results in almost exactly the same power usage (which isn't surprising, since the rendering engine is the same).

The other thing that could make a difference would be content blocking, if you have a content blocking extension installed in another browser. or have it enabled in Min. Using the "stalled" number of each network request in the Chrome devtools, the Min content blocker seems to be slightly slower than UBlock Origin, which seems to be the fastest widely-used content blocker.
