### ISSUE TITLE
Development guidelines?

### ISSUE THREAD

**Issue by z3t0** [minbrowser/min#342]
Hi i am having a bit of trouble figuring out how to setup the repo for development.

For example I tried the instructions in the readme but that gets me minified and uglified code, which is  great for release, but not ideal for development. Is there something I'm missing here

**Comment by z3t0** [comment]
It seems to be that the project is structured in such a way with grunt that it is meant for builds, but running it in dev seems to be difficult / odd?

**Comment by z3t0** [comment]
Okay so I've figured out how grunt works, but there are no source maps...

**Comment by PalmerAL** [comment]
Sorry about that! The instructions weren't very clear; I've updated them in 2b362b7cec2fb736de3b7a58ba281ee1645517c8 to hopefully be easier to understand.

Running ```grunt``` combines all the JS files into ```dist/build.js``` and ```dist/build.min.js```. Once you've run that, you can launch Electron and give it the path to the Min repository by running ```/path/to/electron /path/to/min```.

The function names stay the same in the minified JS, so it usually isn't too difficult to understand what is happening. If you open the Chrome devtools, go to the sources panel, choose "build.min.js", and click the two braces in the bottom-left corner to format it, you'll end up with something almost identical to the original script. You can also change <a href="https://github.com/minbrowser/min/blob/master/index.html#L58">line 58 of index.html</a> to the un-minified version (```build.js```).

Also, the build system will probably be changing once #307 is completed.

**Comment by z3t0** [comment]
I started work on changing to web pack and it's almost complete if you check my fork. Would you be interested in that merging upstream

**Comment by PalmerAL** [comment]
Some sort of module system would be useful, although I haven't researched this enough to know if webpack is the best choice.

@Or3stis was also working on making Min modular, so it might be worth looking at issue #307. Until Min is modular, it's going to be difficult to use webpack etc., since they depend on modules that import each other.

I noticed in one of your commits that you mentioned that the startup time increased after adding webpack? I'm not sure we want to increase the startup time more, so it might be worth looking at why that is happening and how to fix it.

**Comment by z3t0** [comment]
@PalmerAL after more testing i realised the start up time wasnt changing, it was just that my original tests were using unminified full source code. Using the minified version seems to remove the issue

**Comment by Syndamia** [comment]
Closing, because problems seem to be resolved.
