### ISSUE TITLE
This browser should be considered vulnerable until electron updates from Chromium 56.0.2924.87

### ISSUE THREAD

**Issue by jmfgdev** [minbrowser/min#347]
Chromium 56.0.2924.87 has a trove of known security problems. That's what this browser would be based on, no? So it can be assumed that this browser is vulnerable to the problems upstream?

**Comment by PalmerAL** [comment]
Yes, Min would be affected by these problems (and Min is actually based on Chromium 53 right now). This is a result of me not having much time to work on Min over the past few months (so there hasn't been a new release recently), and Electron being behind on Chromium updates. I should have more time to work on Min going forward, so we can release updates faster and reduce the gap, but there's always going to be some gap because of the amount of work it takes for Electron to upgrade to the latest version.

**Comment by PalmerAL** [comment]
The latest release of Min is based on Chromium 58, which is the latest version that Electron supports. I plan to release more often in the future, which should help solve this problem.
