### ISSUE TITLE
About code structure and style (i.e. about the missing contribution guide)

### ISSUE THREAD

**Issue by code-hunger** [minbrowser/min#351]
Hi! I just recently came across this browser and got interested in it.
Now, this is not exactly an issue but rather a question about your coding style and what PRs you'd accept or reject.

I looked around and focused on the settings part of the browser. Going through the source I noticed some things that I would have personally written in a different way. I didn't find any documentation so I suppose here's the place to ask.

First, about these lines:
```
settings.get('keyMap', function (keyMapSettings) {
	keyMap = userKeyMap(keyMapSettings);
```
Grepping for this mysterious global variable I found it was not so hard to track its usage:

```
js/keybindings.js
117:  Mousetrap.bind(keyMap[keyMapName], function (e, combo) {
133:  keyMap = userKeyMap(keyMapSettings)

pages/settings/settings.js
17:	keyMap = userKeyMap(keyMapSettings);
19:	Object.keys(keyMap).forEach(createKeyMapInput);
24:	var key = keyMap[action];
```
The missing `var` is probably a typo (or was it on purpose?).

Another place I'd do some editing but not sure if you'd agree with:
```
function createKeyMapInput(action) {
	var keyMapList = document.getElementById('key-map-list');
	// stuff ...
	keyMapList.appendChild(li);
}
```
As this function is called quite many times (actually depending on `Object.keys(keyMap).forEach(createKeyMapInput);`), I'd extract these lines to the calling function (mainly for elegancy rather than efficiency as this loop is run only once per page load).

My question is, do you find such "fixes" appropriate and would you find them useful or not?
There're also some failing 'standard' tests which deserve fixing.

**Comment by PalmerAL** [comment]
Fixes for things like that are definitely useful!

 To answer your specific question, adding ```var``` wouldn't work because keyMap is being used as a global variable (so ```keyMap = ``` really means ```window.keyMap = ```). The correct fix here is probably to stop using keyMap as a global variable.

The second fix looks fine as well. In general, I'm fine with bug/style fixes, etc. If it's a major change or a new feature, it's better to open an issue first, but otherwise don't worry about it.

The standard tests are failing mostly because of the usage of global variables. There's an issue to switch to modules instead of concatenating JS files together (#307), which would solve a lot of these issues as well.
