### ISSUE TITLE
videos in Google drive don't work through direct link

### ISSUE THREAD

**Issue by ppromet** [minbrowser/min#378]
When someone shares a video through Google drive by direct link, min simply loads a blank page by clicking the url.

However everything is normal when you log in Google drive, click the video and play it directly.

**Comment by PalmerAL** [comment]
I've seen this too. What I think is happening is that Google Drive thinks that Min is actually Chrome (I think based on the user-agent?), and tries to connect to the Google Drive Chrome extension. In the process it does this:
```
function CG(a, b, c, d) {
    if (chrome && chrome.runtime)
        try {
```

```chrome``` is undefined, so this causes an error that prevents the page from loading.

Unfortunately, I'm not sure there's much we can do about this. We could try to emulate the ```window.chrome``` API, but that would cause problems with websites that do browser detection by checking whether that API exists. I think the correct fix here is for Google to either fix their browser-detection so that ```CG()``` is never called the first place, or to change ```if (chrome``` to ```if (window.chrome```, which would prevent the error from occuring. 

I'm not really sure what the best way to contact Google about this is, though.

**Comment by PalmerAL** [comment]
I've added a workaround for this in 6320817fdc0562ccfc7e42214f84c7f581f06eea. Hopefully this doesn't break any other sites.
