### ISSUE TITLE
Help: state and DB

### ISSUE THREAD

**Issue by doreminiature** [minbrowser/min#388]
Hello, @PalmerAL 

**Edited: found a solution.**

We are implementing new widget for Miniature web browser, it is similar to overlay widget you have in Min but different in presentation.

Basically it is a tasks tab bar (we call it collections, so collection tab bar) and it renders 5 recent collections you visited. As shown https://i.imgur.com/4F9rxbU.png, collections tab bar is on the top.

Consider this scenario: https://i.imgur.com/4BpGHRx.png
We have one collection and 4 empty collections slots. If I click on empty collection slot input appears and I may enter new collection title then hit enter.

Just as with overlay widget we may create, rename tasks (collections) within our widget.

So we render tasks in this widget and when we change title we are adding new data to the tabState object. But we could not find a method that sends updates to DB. 

And we use ugly solution:
`document.querySelector('#add-tab-button').click()`
New tab creation has mechanism that sends tabState to DB. But we could not figure it out.

Can you guide us on what method leads or how to send tabState data to database without creating new tab?
https://github.com/doreminiature/miniature/blob/3d17dc320539395281b33bf725b2b6a1d54f1304/js/collectionTabs.js#L374

Thanks.

**Comment by doreminiature** [comment]
I think I found it.
`sessionRestore.save()`

**Comment by PalmerAL** [comment]
Yup, that's right. The session data is actually stored in localStorage instead of the database (since the database takes several seconds to open, and waiting for it would delay startup too much).

I'm interested to see what you come up with with this project. I haven't been following it too closely until now, but reading your description in doreminiature/miniature#2, I can see how some of the things you describe would be useful. Min works pretty well once you get used to it, but it's pretty difficult to discover new features, and it seems like a lot of people have difficulty using Min because of this. I'll be looking forward to seeing if you can solve this with the design you've described.

**Comment by doreminiature** [comment]
@PalmerAL Thanks. We hope not to disappoint you. Hope not to distract you with questions too much.
I have quick [presentation ](https://www.youtube.com/watch?v=UFQeau9ue80&feature=youtu.be)of Miniature, we managed to implement (actually features shown are hardcoded, lol) it during 2 days.
