### ISSUE TITLE
Let users disable two-finger swipe for navigation

### ISSUE THREAD

**Issue by qoobi** [minbrowser/min#39]
I often go back or forward by accident, which is disturbing, and I'd prefer to disable this feature.

**Comment by burnoutberni** [comment]
I agree, this is a feature that constantly bugs me, because I'm trackpoint-only user, so I can not accurately scroll vertically or horizontally.

The question for me is, what do we want to be able to disable? Only swipe navigation (back/forward) or all swipe controls (incl. closing tabs, opening tasks view,…)? I don't care about the latter, because it doesn't happen accidentially (at least to me), but I really care about the former.

Regarding https://github.com/PalmerAL/min/issues/81:
> I think it would be good to avoid having settings if possible, though, and instead figure out if the default can be changed. For example, with the swipe gestures, it's probably better to adjust them so they accidentaly trigger less rather than creating a setting to turn them off.

I theoretically agree, but I don't think it's a viable solution in this case. I tried changing the scroll values in 
```js/webview/swipeEvents.js``` and even with ```totalMouseMove > 1000``` I still get a couple of false positives while scrolling pages (and every single false positive is a pain in the butt).

**Comment by mardukbp** [comment]
+1 I have the same problem and would like to disable gestures for back/forward.

**Comment by benhourigan** [comment]
+1. Arguably should not be on by default.

**Comment by PalmerAL** [comment]
This was fixed a few months ago in 1.6.0.
