### ISSUE TITLE
Save and restore session menu commands

### ISSUE THREAD

**Issue by razzintown** [minbrowser/min#395]
Can the session backup feature in #393 have a command in the File menu? It could be "Save Session As" right next to "Save Page As". This could lend itself to "Open Saved Session" as well. 

I'm weary of adding clutter, but this might be core functionality. Since Min doesn't use bookmarks, I see the Task as having a permanent aspect to them. Saving sessions in the GUI is more user friendly than copying the Min folder.

**Comment by PalmerAL** [comment]
I can see how this would be useful, but I'm not sure about adding a way to manage sessions. Tasks kind of function as sessions right now, since they persist after the browser is restarted, and you can leave a task in the overlay and pretty much ignore it until you want to open it again. A "duplicate task" option might help with this, since you could leave another task for later with the tabs you had, and continue modifying the task you are using. We could also add some kind of "archived tasks" area where you could move tasks to, although that increases the complexity of using tasks which isn't great.

Also, Min does have bookmarks right now, but they aren't very visible or full-featured (open the searchbar and click the star icon to bookmark a page, use the !bookmarks command in the searchbar to view them). So I guess another option would be to add an option like "bookmark all tabs". Then we could display bookmarks that were created at the same time in groups, and provide an option to open them all together.

**Comment by razzintown** [comment]
Thank you for the great explanation. I agree that a session export menu is probably not necessary.

**Comment by PalmerAL** [comment]
To be clear, I'm not saying that we shouldn't try to solve this problem; rather, that I'm not sure another set of menu items is the right way to do it. I think we could probably modify tasks to make them more useful for this; I agree that Min doesn't do a great job of solving this usecase right now, particularly if you're using the tasks list as a to-do list rather than an archive.

**Comment by razzintown** [comment]
I like your ideas for more Task actions. I use the "Duplicate Tab" feature very often in Chrome, and I'd like to see that in Tasks view as well. 
Perhaps Archive Tasks feature would be closely related to the Recently Closed Tabs feature in #3 .
