### ISSUE TITLE
MailTo links wont work

### ISSUE THREAD

**Issue by SpecialBomb** [minbrowser/min#411]
When a mailto link is clicked, the system default email client does not respond to it.

**Comment by PalmerAL** [comment]
This is fixed in #428.

**Comment by incanus** [comment]
I am seeing this again — `mailto:` links don't do anything. Mac Big Sur, latest Min version.

**Comment by PalmerAL** [comment]
This regressed in 10d312f97e803d0c7f5525a78e723ec0e3a359b4, because the protocol handler is being registered to the wrong session now (see [here](https://www.electronjs.org/docs/api/protocol#using-protocol-with-a-custom-partition-or-session): "If you don't specify a session, then your protocol will be applied to the default session that Electron uses").
