### ISSUE TITLE
Dear Min.

### ISSUE THREAD

**Issue by doreminiature** [minbrowser/min#434]
Hello, just wanted to greet and thank you guys @ Min team.

We at Miniature released first public version today and invite you to have a [look](https://github.com/doreminiature/miniature/blob/master/README.md) and [play with it](https://github.com/doreminiature/miniature/releases)!

**Comment by PalmerAL** [comment]
Cool! I haven't tried it out much yet, but so far I've noticed a couple of small things:

* Looking at the Mac builds, it looks like you're using the Min icon instead of the Miniature one. I believe you need to replace the <a href="https://github.com/doreminiature/miniature/blob/master/icon.icns">icon.icns</a> file to get the Mac build to use the correct icon.
* You may also want to consider increasing the opacity of some of the toolbar buttons; it's a bit difficult to see the controls.

Otherwise, it does seem like you have some interesting ideas with this. I'll be interested to see how it develops!

**Comment by doreminiature** [comment]
> You may also want to consider increasing the opacity of some of the toolbar buttons; it's a bit difficult to see the controls.

You mean back & forward buttons, or overall? Back & forward are "disabled" from the start so a bit transparent.

**Comment by PalmerAL** [comment]
I meant the overall buttons, although I suppose it is a personal preference to some extent.

Also, I realized that you probably need a Mac to make an ICNS file for the package icon. If you're developing Miniature on another platform, I'd be happy to make a PR to fix the icon file.

**Comment by doreminiature** [comment]
Thanks for suggestions. I will look into it.
Yes, currently I don't have a mac and only can ask my friend to build sometimes.
PR sounds great, welcome!

**Comment by PalmerAL** [comment]
OK, will do.

**Comment by PalmerAL** [comment]
Do you have a higher-resolution icon file somewhere? You need a 1024x1024px imge to create an icns file; the image in icons/icon265.png is only 512px.

**Comment by doreminiature** [comment]
Yes, please. https://i.imgur.com/MbNFqiI.png

**Comment by doreminiature** [comment]
Btw, as a Mac user what is your reaction when you don't see traffic lights controls and instead see controls on the right? I mean, Mac has a very opionated GUI conventions (traffic lights to the left of the window) and it is kind a unacceptable in my design.

**Comment by PalmerAL** [comment]
PR: doreminiature/miniature#4.

**Comment by PalmerAL** [comment]
Not having traffic light controls does seem a bit odd; I don't think I've ever seen any other app do that. I would probably go ahead and add them, although it doesn't look that great since the navbar isn't the right height to match:

<img width="1438" alt="screen shot 2017-10-17 at 9 15 46 pm" src="https://user-images.githubusercontent.com/10314059/31697976-63296b7c-b380-11e7-93be-960d9c221c89.png">

Also, in order for things like clicking and holding the maximize button to enter split-screen, you would need to use the native controls, although I'm not sure how many people actually use this.

**Comment by doreminiature** [comment]
I see. Actually it looks not too bad with traffic light on the left, if I make overview button width a bit larger, so + sign aligns with menu. Thanks.
