### ISSUE TITLE
google.com complains about "... older version of Chrome"

### ISSUE THREAD

**Issue by we3geeks** [minbrowser/min#485]
I just updated to v1.7.0, and when I go to google.com, it shows the following message: "We've detected you're using an older version of Chrome. Reinstall to stay secure". See attached screenshot.

Is this an issue with the user-agent string or the version of Chrome or something else?

![min-20180121](https://user-images.githubusercontent.com/2390335/35197509-4f1ab0ec-fe9d-11e7-98a9-0ef587636fd2.png)

**Comment by PalmerAL** [comment]
The latest release of Electron is based on Chromium 59, which is a couple versions behind the latest release. The master branch is based on Chromium 61, and it seems to work OK, so I'm hoping they make a new release soon. If they don't, I might just compile it myself and make a new release of Min based on that. After that, https://github.com/electron/electron/pull/11459 needs to be merged to upgrade to Chromium 63.

**Comment by dbfreem** [comment]
Won't thia always be an issue though? Since it's a two step process to get the latest version of chromium into min.

Electron gets the upgrade, then min.

How does electron handle this if their master branch is behind the latest version of chromium? Is there a standard number of versions behind google allows before flagging the bowser as old? These are all just questions I thought of as I was reading this.

**Comment by PalmerAL** [comment]
> Is there a standard number of versions behind google allows before flagging the bowser as old?

There is, I'm not sure exactly what it is though. Right now, we're on Chromium 73 (two versions behind the latest release), and I don't see the warning, so probably at least that much?

Electron's gotten a lot faster with upgrading to new Chromium releases recently ([as explained here](https://electronjs.org/blog/12-week-cadence)), so as long as we continue making new releases of Min reasonably quickly this shouldn't be as much of an issue.
