### ISSUE TITLE
Basic Window controls Not Effective

### ISSUE THREAD

**Issue by aplatypus** [minbrowser/min#504]
I wanted to try this out.  But it is almost impossible to get the window to fit on the screen.

I normally expect to be able to do:

1. Move (20%)
   - It is very difficult to "grab" the frame and consequently move it
   - I put 20% since it works about 20% of the time.
1. Resize (x)
    - Horizontal is just working -- very difficult
    - Have had NO success with vertical / height changes
    - As a result I can't fit the window on the laptop screen
1. Minimise (/)
1. Maximise (/)
1. Restore (x)
   - Restore restores to some huge bigger than the display window that the resize controls barely cope with.
   - see item 2.

I don't know how much of this is electron and how much is the app.  

---

Used on Windows 10 64-bit 
Don't know what build Min is, you don't have and About box in the Help menu
The install came from zip file: v1.7
- Min-v1.7.0-win32-x64.zip

which is also confusing since it is 64-bit not Win32.

## Suggestions

- Add About box
- Include Readme with the install folder
- Implement the default controls e.g. Alt/Spacebar, these even apply to on linux (at least on my versions)

**Comment by PalmerAL** [comment]
Thanks for reporting this!

> It is very difficult to "grab" the frame and consequently move it

We could make the drag area at the top of the winow taller; the downside is this reduces the amount of space available for websites. I'm not sure what the right height is.

> Horizontal is just working -- very difficult

Not sure what we can do about this. In order to avoid showing the titlebar, we're using a frameless window, which removes the border around the window. I'm not sure if there's a way to add it back; we could possibly emulate it in HTML instead, but I'm guessing it would be hard to get it to match the original.

> Have had NO success with vertical / height changes

There was a bug in 1.7 that prevented vertical dragging from the top edge from working. This was fixed in 67d3385c8af91a49ace18e21b9c38198cca9bd1b, which will be included in the next release. Dragging from the bottom edge should work already; does this not work for you?

> Restore restores to some huge bigger than the display window that the resize controls barely cope with.

I can't reproduce this; is there anything unusual about your setup that could possibly cause this?

> which is also confusing since it is 64-bit not Win32.

The Windows API is still called "win32" for some reason, even the 64-bit versions: https://social.msdn.microsoft.com/Forums/en-US/ea0e5ff5-d5f9-4764-9abd-e921a31feca9/whats-win32-and-64bit?forum=netfx64bit

> Add About box

You're right we should add that; I'll look and see if there's an easy way to do that.

> Include Readme with the install folder

Good idea, although I think the plan is to eventually get rid of the install folder completely and replace it with an installer.

> Implement the default controls e.g. Alt/Spacebar, these even apply to on linux (at least on my versions)

It looks like the alt-spacebar shortcut is conflicting with pressing alt to show the standard menu, I'll look into fixing that.

**Comment by PalmerAL** [comment]
> You're right we should add that; I'll look and see if there's an easy way to do that.

It turns out the built-in about dialog only exists on Mac; if we want one on Windows we have to write our own, which seems like a lot of work for not much benefit.

**Comment by code-hunger** [comment]
What is the problem with a
```
dialog.showMessageBox(window, {
type: 'info',
text: 'Min ' + version + "\n. Official repo:" + github_url
});
````
?
https://electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options-callback

**Comment by PalmerAL** [comment]
@code-hunger Yeah, that's a good idea, I kind of forgot about that when I was looking into this.

**Comment by aplatypus** [comment]
Personally an Info or About box is _**NEVER**_  too much trouble.

Today I found I have two versions of ssh on a machine.  One comes with `git`it has no versioning so I can't check if it has a OpenSSL vulnerability or not.  The _proper_ `ssh` file from the GNU people show the version and OpenSSL version used.  _Thumbs up!_

It is all about tracability and governance these days.

**Comment by PalmerAL** [comment]
I've added an about dialog in 309369ac150a1e21e6375fc01a92467d1bb8ee68.

**Comment by Syndamia** [comment]
I couldn't replicate any of the problems @aplatypus was having in the newest version (`1.16`), and his suggestions seem to be implemented.
