### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by lauriefitzherbert** [minbrowser/min#512]
I'm extremely new to Min--like 5 minutes of use. The Min Tour gives keyboard commands that use the looped square symbol that I have always taken to mean the "windows" labeled key. These commands did not work.  The settings page of Min has different keyin commands set up alrIeady and use the Ctrl- format. If Min Tour means ctrl by the looped square symbol, it would be helpful to newbies to see a reference on the page for what key sequence you are implying. 

Also, my second observation was my first search in Google. Google "detected" that I was using an outdated version of Chrome and suggested that I make an update. (Long ago, I liked Chrome...so it's not offensive, completely. But, this error message from google could cause someone to download the latest version of Chrome. I know from an old server that I could read a visitor's browser version--is there something that can be done to make Min show up as Min?

I like your product so far. You are replacing Firefox that has caused my system to freeze up for the very last time.  Thank you for all your work and I hope my suggestions help and not offend. You have a great piece of software.  Thank you!

**Comment by PalmerAL** [comment]
>  The Min Tour gives keyboard commands that use the looped square symbol that I have always taken to mean the "windows" labeled key. These commands did not work. The settings page of Min has different keyin commands set up alrIeady and use the Ctrl- format. If Min Tour means ctrl by the looped square symbol, it would be helpful to newbies to see a reference on the page for what key sequence you are implying.

Are you talking about the https://minbrowser.github.io/min/tour/ or about https://github.com/minbrowser/min/wiki ? You're correct that it corresponds to the Ctrl key, ⌘ corresponds to the Command key on Mac. For the tour page, it looks like we only show shortcuts in the screenshot near the bottom, so we should probably have separate sets of screenshots for each platform. For the wiki page, we could change the shortcut listings to something use something like ```mod+__``` instead and have an explanation at the top.

> Also, my second observation was my first search in Google. Google "detected" that I was using an outdated version of Chrome and suggested that I make an update. (Long ago, I liked Chrome...so it's not offensive, completely. But, this error message from google could cause someone to download the latest version of Chrome. I know from an old server that I could read a visitor's browser version--is there something that can be done to make Min show up as Min?

Google's actually detecting this mostly-correctly here. Min is based on Chromium (the same browser engine that Chrome uses), and the version we're using is a few versions behind the latest version. Ideally, we would always be using the latest version of Chromium, but it's a lot of work to upgrade (for example: https://github.com/electron/electron/pull/11230), and so the Electron team usually takes a bit to finish the upgrade. We could change the user-agent and pretend to be a newer version of Chrome, but Google sometimes enables different features based on your browser version, so that probably isn't a good idea. Having Google identify Min specifically would also be nice, but that would require them changing their browser-detection code, and there isn't really anyone we can contact to ask them to do that.

>I like your product so far. You are replacing Firefox that has caused my system to freeze up for the very last time. Thank you for all your work and I hope my suggestions help and not offend. You have a great piece of software. Thank you!

Thanks!

**Comment by PalmerAL** [comment]
I've updated the Wiki page to hopefully be more clear: https://github.com/minbrowser/min/wiki/Home/0ec726e056d932098c29e4b284d4b09f630b89c8.

**Comment by lauriefitzherbert** [comment]
> Are you talking about the https://minbrowser.github.io/min/tour/ or about https://github.com/minbrowser/min/wiki ? 

I was talking about the browser actions part of the tour via the link that is in the help menu within the browser. I think you fixed it already. Thanks. The explanation now at the top makes it clear for non-Mac users. I thought that symbol was the Super key.  As far as the ID of the browser  I'd think that would be in a header file of the program where the browser name (or codename) could be modified and just read by the server (google or whoever). But, that is why I am not a programmer.

And here is my biggest complaint of all!!!!(not)  I couldn't view a couple rag newspapers because your ad blocking works so wonderfully! They blocked me and sent a screen message that their content was sponsored and paid for by their advertisers  which I will assume was a freidian slip!!!! Thank you Thank you Thank you!   

I didn't crash all day long or have to wait. It reminded me of the old days before advertisers got their claws into it, when we  literally "surfed" the Internet.
