### ISSUE TITLE
Latest Version not in Linux App Store

### ISSUE THREAD

**Issue by CorbsEditor** [minbrowser/min#515]
![image](https://user-images.githubusercontent.com/26362558/37557335-6729ea10-29d9-11e8-9a49-28a2bd06e69f.png)
The Linux Distro I am using is Deepin OS, I saw Min in there and noticed that it's not the latest version.

**Comment by PalmerAL** [comment]
Hmmm, I'm not really sure what to do about this. I never uploaded that to the store, so I'm assuming that we'd have to contact whoever did to get them to update it. Beyond that, I can't actually look at it, because my internet connection to the store is extremely poor. On appstore.deepin.org, after waiting like 5 minutes for the page to load, I can't find it there. I'm assuming the listing is on appstore.deepin.org (what's the difference between these anyway?), but I can't get that one to load at all. Even if I could somehow get control over the store listing, I doubt I could upload a new binary anyway because of the connection issue (the store is loading at around 5kbps, so assuming the upload speed is the same it would take around 3 hours to upload a new binary).

**Comment by CorbsEditor** [comment]
Yeah, I don't blame your internet. Deepin is mostly located in China, updates on the system takes forever xD!
But I'll contact Deepin right away.
