### ISSUE TITLE
DRM protected content and History List

### ISSUE THREAD

**Issue by antoniobritolte** [minbrowser/min#546]
Min browser does not accept playing DRM content, probably because it's lacking the widewine plugin.
Another minor inconvenience is the absence of the full browser history, already said at #222 and #116 .

![screen shot 2018-04-16 at 22 35 55](https://user-images.githubusercontent.com/38446675/38844221-db7eeb84-41c8-11e8-8876-d9cce6996db8.png)

**Comment by PalmerAL** [comment]
DRM is issue #161, although I doubt we're ever going to bundle Widevine. If you want to use it, there are instructions here on how you can patch Min to make it work: http://electronjs.org/docs/tutorial/using-widevine-cdm-plugin.

Full history list is a good idea, but since there's already an issue for it I'm going to close this one.

**Comment by elzii** [comment]
1. @PalmerAL the link you provided no longer works. Do you have an updated one?

**Comment by VoxAndrews** [comment]
@elzii Not sure if this is the same type of thing but it seems on a similar topic based on the name

http://electron.ebookchain.org/en/tutorial/using-widevine-cdm-plugin.html
