### ISSUE TITLE
installing in windows 7

### ISSUE THREAD

**Issue by tonyg123** [minbrowser/min#577]
How do you install it on Windows 7? there seems to be only one zip file to download and it seems to be a Linux file. Can it work on windows 7? How do you install it?

**Comment by tonyg123** [comment]
the error message i get when i try to install it is :
script 
C:\Users\.....\Downloads\Min-v1.7.0-win32-x64\Min-win32-x64\resources\app\node_modules\electron-installer-debian\src\installer.js
Line: 3
Char: 1
Error: object expected
code: 800A138F
source: Microsoft JScript runtime error

**Comment by PalmerAL** [comment]
It should work on Windows 7. You can download the windows file from here: https://github.com/minbrowser/min/releases (although it should show up on the main download page at https://minbrowser.github.io/min/ as well) - you'll want the "win32-ia32" or "win32-x64" files. 

There isn't an installer yet, so you'll have to run the Min.exe file directly - I would probably just save the folder somewhere, and pin the exe to your taskbar.

**Comment by dbfreem** [comment]
I do think this is an important feature to get implemented. If the brower is going to grow in popularity it should be super simple to install. If not then the audience of who would use the browser is effectively limited to the people who know how to unzip, save to a standard location, and create a short cut to the exe without needing to come find this issue. Most people will not take the time to figure it out if they get stuck after the download. I would venture to guess quite a few people download the windows version and never use it becuase they don't see a windows installer after the download.

**Comment by PalmerAL** [comment]
@dbfreem I definitely agree this is something we should do; it hasn't been a very high priority, but maybe it should be. Even when we do fix this, I expect that the audience for Min is mostly going to be limited to people that know how to unzip a file anyway, both because non-technical users don't tend to switch browsers very often, and also because I think Min's UI tends to be less approachable than other browsers - but if we can attract a wider audience, that would be a good thing, so we definitely should work to make it easier to install.

**Comment by PalmerAL** [comment]
This has been fixed in 1.10.
