### ISSUE TITLE
Visiting Bookmarks

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#579]
Not an issue, just a question since i can't find it! How can i view all my bookmarks?

**Comment by code-hunger** [comment]
In the list of issues there's a searchbar - if you have any other questions, you'll most likely find the answer there. In this case, the same question has been asked here: #356.

**Comment by code-hunger** [comment]
PalmerAL, There was somewhere a discussion about making pages equivalent to chrome's "about:history/settings/bookmarks..." etc. where you said it would be nearly impossible to expose min's data to the pages. Do you know where it was? Because I feel it is quite doable if instead a native min tab we open a separate window that doesn't use the webview but accesses the data directly.

**Comment by ateymuri** [comment]
@PalmerAL  Thank you. And how can one remove a bookmark from the bookmarks list?

**Comment by PalmerAL** [comment]
@code-hunger That's #554 (and it's not impossible, it would just be more complicated and require us to be more careful about not to introduce security issues).

**Comment by PalmerAL** [comment]
@ateymuri If you have a trackpad, you can swipe left on the item to delete it (we should probably add a button as well, but we haven't done so yet). Otherwise, you can visit the page again, and click on the star icon in the searchbar to un-bookmark it.

**Comment by dbfreem** [comment]
So is this issue to add the remove bookmark button and the other issues are covered by the referenced issues above?

**Comment by PalmerAL** [comment]
I think so. I actually added a remove bookmark button in 1.10, so I think it's fine to close this.
