### ISSUE TITLE
Feature Request: Enable scroll with touchpad while organizing in TO

### ISSUE THREAD

**Issue by clayton-grey** [minbrowser/min#594]
If your task list is longer than screen height, you cannot scroll while dragging. As such you need to drag/drop/scroll on repeat to move a tab to a task off screen. (OSX)

**Comment by code-hunger** [comment]
What about a "send to" button for each tab instead? When clicked, a list of all tasks appears and the user selects a target task for the tab.
Sounds better than scrolling from bottom to top while draging.

**Comment by PalmerAL** [comment]
It looks like our Dragula [doesn't support this](https://github.com/bevacqua/dragula/issues/482), so we'll need to find another library that does.

**Comment by PalmerAL** [comment]
Fixed in 30f41c6dc6a68ab9acd210e93d4dd30751df873d; if you drag the element near the top or bottom of the screen, the list will start scrolling until you move it away from the edge or drop it, which matches the behavior of most other apps I've seen with drag-and-drop lists.

A button-based interface for rearranging tasks would probably be nice as well, but that's probably better as a separate issue.
