### ISSUE TITLE
Not really an issue issue...

### ISSUE THREAD

**Issue by tday0501** [minbrowser/min#620]
First timer here... trying to add some ux, how do I package the files into an application. I believe it's done through terminal, but can't seem to run the right command. Help please!

**Comment by PalmerAL** [comment]
Sorry you're having issues with it! The first thing to do is to install Node. There's an installer that you can download and run here: https://nodejs.org/en/.

Once you've done that, you'll need to install Grunt, by running `npm install -g grunt-cli` in the terminal (you'll need to be an administrator to do this).

Once you've done that, switch to the Min folder:
```
cd <insert path>
```

Then install the required dependencies:
```
npm install
```

After that, you should be able to create the application file, by running either `grunt windowsBuild`, `grunt macBuild`, or `grunt linuxBuild` depending on which OS you're using.

**Comment by tday0501** [comment]
So essentially I can't package it unless I'm an admin?

**Comment by PalmerAL** [comment]
It looks like you might be able to install Grunt without administrator access if you do this: https://github.com/npm/npm/issues/3139

Alternatively, you don't have to create a package in order to run Min; if you just want to run it for development purposes, you can do this:
* Download the Electron binary from here: https://github.com/electron/electron/releases
* Go to the Min folder in the terminal, and run `npm run build`.
* Run this in the terminal
```<path to electron> <path to min folder>```

**Comment by PalmerAL** [comment]
Grunt has been replaced with custom build scripts, so I don't believe this is an issue anymore. If you're still running into issues with this, please feel free to open a new issue.
