### ISSUE TITLE
After using Min for a few weeks...

### ISSUE THREAD

**Issue by ghost** [minbrowser/min#653]
I 've tried to read most of the issues so I don't repet any, anyway... here's my input (running 1.8 in W10 x64)

- Electron\logs empty folder is created in in %AppData%
- Tabs are created by default next to the current, I'm really used to all the browsers open the tabs at the end (or an option to switch between both)
- In #636, not just a "Download link" but also "Copy link adrress"
- Any sort of status bar is really useful, at least for the links (like Chromium)
- A command line option for storing profile information (aka, a way to be portable)

Download management is very important, integrate aria2+AriaNG will be pretty easy and really awesome.

Thanks for all the hard work and this useful piece of software.

**Comment by PalmerAL** [comment]
Thanks for the feedback!

> Electron\logs empty folder is created in in %AppData%

I think Chromium does this intentionally, so I don't think there's anything we can do about this unfortunately.

> Tabs are created by default next to the current, I'm really used to all the browsers open the tabs at the end (or an option to switch between both)

Aside from it being different, is there a particular workflow you find difficult with the tabs working this way? I think it generally makes more sense to do this than opening them at the end, so I'm kind of reluctant to do this, but I guess if enough people want it we could do it.

> In #636, not just a "Download link" but also "Copy link adrress"

There should be a "copy link" item already that works for downloads; is that not showing up for you?

> Any sort of status bar is really useful, at least for the links (like Chromium)

I feel like this would add to much clutter, although I can see how it would be easier to preview links this way. (In case you haven't seen it, opening the context menu on a link will show you what the link is without having to navigate to it).

> A command line option for storing profile information (aka, a way to be portable)

You mean something like the `--user-data-dir` flag in Chrome?

> Download management is very important, integrate aria2+AriaNG will be pretty easy and really awesome.

We're planning to add a download UI using Chromium's built-in download utilities in #91. I haven't heard of aria2 before, is there something that makes that better than the built-in option?

**Comment by lordhellraiser** [comment]
- As for the empty folder, if it's something brought by Chromium the only possible thing to do is to delete at shutdown
- It doesn't affect my work-flow (too much), I guess I'm used to that since late 90's having software opening the tabs at the end instead of next to current. But, if you open let's say 5 links in background at the same time, you go to the first tab (last link) and it'll take considerable time to load, meanwhile the last tab (first link opened) is already loaded. In other words right now is LIFO and me (and I guess a lot of people) is used to FIFO.
- Got it, now I can grab links for my Autohotkey script and send it to Aria2. Anyway... feel more natural just hover the mouse and watch the status bar rather than right click (some sites disable this functionality) the link.
- Exactly
- Aria2 its a CLI utility equally powerful to wget and CURL, it can communicate with sockets. Right now I use Aria2 with Chromium and "Camtd" extension (bundles AriaNG, a wonderful UI). Everything is open source, so... its not far fetched.
