### ISSUE TITLE
Enhancement: Scroll to the end when opening a new tab

### ISSUE THREAD

**Issue by revolter** [minbrowser/min#662]
Currently, if you have the tab bar full of tabs, select the last tab, and cmd + click open a new one, it opens outside the scroll area, so you don't see it at all. The only thing that changes is the white scroll bar underneath the tabs, but that's not that visible. I often find myself opening it multiple times thinking it did not work.

**Comment by PalmerAL** [comment]
Thanks for pointing that out! Fixed in 32802048152064ce7391b6fa6f33de0a369b2f88.

**Comment by richbordoni** [comment]
I'm having the same issue on Min 1.12, W10 x64. If you have multiple tabs open so that the tab bar becomes scrollable, and you open a new tab, Min scrolls all the way back to the beginning of the tab bar causing the newly opened tab to be out of sight. See here:

![min](https://user-images.githubusercontent.com/8562062/74366326-d0697d80-4d9d-11ea-876c-7df41aeb6292.gif)

The same issue also happens if you open a new tab and then just close the URL bar without navigating to any site.
