### ISSUE TITLE
What does auto-run-policy parameter do?

### ISSUE THREAD

**Issue by hezral** [minbrowser/min#674]
This is more of a question. I'm running Min by using IPBind to bind it to a specific ip so the traffic only routes to it. On version 1.7 this works perfectly, but on 1.8 it seems like the traffic doesn't go through at all. 
I took a look at the command line parameters while 1.8 was running and saw that its different with 1.7 where 1.8 had this auto-run policy.

**Comment by PalmerAL** [comment]
The `--autoplay-policy` flag (which I think is what you're talking about) controls whether or not videos automatically start playing on websites (to disable this change: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes); I wouldn't expect it to have any effect on where network requests get sent.

I'm not sure why this wouldn't work in 1.8; most likely it's because of a change made in either Chromium or Electron. Does it work correctly in Chrome?

**Comment by hezral** [comment]
Thanks. it was the only difference i saw in the command line parameter that ran the Min.exe instances. It was just a hunch. 

I haven't tested with Chrome because last time it doesn't work as Chrome creates multiple instances and IPBind couldn't get it. 

I've reverted back to 1.7 for now and it worked until 1.7. 
Will wait for a new version.

**Comment by PalmerAL** [comment]
Let me know if you figure out why it doesn't work, if there's something we need to change to make this work in 1.8 I'd be happy to add it (although I expect this is a general Electron issue, you might want to see if you can reproduce it with other Electron apps as well and open an issue there).

**Comment by hezral** [comment]
Sure, will do. Thanks!

**Comment by hezral** [comment]
Update: I figured out how to fix it but not sure how its affected. Basically from googling, i found that adding "--no-proxy-server" solved this issue. Min's traffic uses the route that i set from ForceBindIP.exe. 
This seems related to chromium which Electron is using.
