### ISSUE TITLE
alt-tab

### ISSUE THREAD

**Issue by LukaFX** [minbrowser/min#689]
when you alt-tab from another windown to min the right click meno automaticly opens were the mose is, its kinda annoying.

**Comment by PalmerAL** [comment]
I can reproduce this if I click on the Min window in the alt-tab window, and then release the alt key. This is probably because of 37d474421d88eebc515822db2ebbbce2dea0661e; we need to check for both a keydown and a keyup event (or just disable the alt shortcut on Windows entirely, I'm not sure that it makes sense now that we don't have a traditional menu bar).

**Comment by PalmerAL** [comment]
This was fixed in the latest release.
