### ISSUE TITLE
Searchbar bugs on Mac and other questions

### ISSUE THREAD

**Issue by sachali** [minbrowser/min#692]
I'm a macOS user and found 2 bugs with the searchbar:
1. Sometimes when I enter an address the browser can't handle properly and shows and an error message "This address is invalid." For example if I type in "youtube.com" the address becomes http://%08youtube.com/
![screen shot 2019-01-05 at 21 47 23](https://user-images.githubusercontent.com/46397851/50725506-901ae300-1139-11e9-9664-39ea76ed4abf.png)
2. Also sometimes when I type in non latin scripts to do a search the input is not decoded properly becomes garbled, I'm not sure what trigers it.

In addition,
3. How do I delete a bookmarked page? Since I work with google slide, duplicating a slide is also ⌘ + d and I want to delete these bookmarks but couldn't find a way to do it.
4. Can you increase the contrast between the color of current tab and other tabs. It's not very obvious to me and sometimes I have a hard time to find where it is to close it?
5. Is there a way to integrate instapaper or other read it later services?
6. I would really love it if you plan to release an iOS version!!

Thank you so much in advance for answering my questions!

**Comment by PalmerAL** [comment]
Thanks for the feedback!

> Sometimes when I enter an address the browser can't handle properly and shows and an error message "This address is invalid." For example if I type in "youtube.com" the address becomes http://%08youtube.com/

Which keyboard layout are you using when this happens? %08 corresponds to a backspace character, but I can't find any keyboard layout that results in a backspace character being inserted into the text field, rather than just deleting the text.

> Also sometimes when I type in non latin scripts to do a search the input is not decoded properly becomes garbled, I'm not sure what trigers it.

Do you have an example of a character that causes this? I'm guessing this because we're using [event.keyCode](https://github.com/minbrowser/min/blob/master/js/navbar/tabBar.js#L231), which doesn't work for some characters, we probably need to use [event.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) instead, but it would be good to confirm that this is actually what's causing the issue.

> 3. How do I delete a bookmarked page? Since I work with google slide, duplicating a slide is also ⌘ + d and I want to delete these bookmarks but couldn't find a way to do it.

The only way to delete a bookmark directly from the bookmarks list is to swipe left on it (which requires that you have a trackpad); otherwise, you can click on the bookmark to open it, and then open the searchbar and click on the star again to un-bookmark it. We really should have a button to delete these directly, I'll try to add one soon.

> 4. Can you increase the contrast between the color of current tab and other tabs. It's not very obvious to me and sometimes I have a hard time to find where it is to close it?

Is this an issue on every site, or just some? I've made a couple of changes recently to increase the contrast on certain backgrounds that were particularly hard to see (fc07e1d6a1026769fc3b7c0efba3cafecbfec81a, 72d8d778df34d3e0d3a88677c0a046be039bf044), but if this is a more general issue we might want to consider increasing the contrast for every site as well.

> 5. Is there a way to integrate instapaper or other read it later services?

I don't think there's any easy way to do that, because we don't support extensions, althought it might be possible to write a [userscript](https://github.com/minbrowser/min/wiki/userscripts) that saves articles to Instapaper using their [API](https://www.instapaper.com/api).

Min also includes a built-in reading list feature (View menu > reading list) with all of the things you've opened in reader view, although this might not be what you're looking for (since you can't sync it with more than one device).

> 6. I would really love it if you plan to release an iOS version!!

A mobile version would be interesting! I think there's definitely a lot of opportunity to improve on existing mobile browsers, although I'm busy enough just working on the desktop version of Min, so I doubt that I'm going to do that anytime soon. (and Apple's restrictions make it pretty difficult to compete with Safari anyway, so it would probably make more sense to focus on Android if we did do this at some point).

**Comment by sachali** [comment]
> Which keyboard layout are you using when this happens? %08 corresponds to a backspace character, but I can't find any keyboard layout that results in a backspace character being inserted into the text field, rather than just deleting the text.

As seen in the screenshot, my keyboard layout is English (U.S.), this doesn't always happen, and I also just tried to backspace before typing in an address and the error message didn't happen.

> Do you have an example of a character that causes this? I'm guessing this because we're using event.keyCode, which doesn't work for some characters, we probably need to use event.key instead, but it would be good to confirm that this is actually what's causing the issue.

I don't right now. I also tried to replicate the situation but the browser has been working fine. I don't think it's the specific characters though because i remember searching the same thing but sometimes it worked and other times it didn't. Will get back to you when this happens again.

> Is this an issue on every site, or just some? I've made a couple of changes recently to increase the contrast on certain backgrounds that were particularly hard to see (fc07e1d, 72d8d77), but if this is a more general issue we might want to consider increasing the contrast for every site as well.

It's just some websites (Github, for example), but maybe a more fundamental solution is to make the text bold or some other texual emphasis? I took 2 screenshots and for whatever reason they don't seem that different, but the first one provides enough contrast for me on my Macbook Air screen  and the second one is barely recognizible.

![screen shot 2019-01-07 at 01 51 44](https://user-images.githubusercontent.com/46397851/50739748-705dea80-121f-11e9-8848-598be4639def.png)
![screen shot 2019-01-07 at 01 51 58](https://user-images.githubusercontent.com/46397851/50739750-75bb3500-121f-11e9-9f66-01ed87e7fc78.png)

**Comment by sachali** [comment]
> OK, let me know if it happens again. We should probably just change the keyboard event handling any way, maybe that will fix the issue.

Yea so it just happened again. The text I searched was **台達** and it became **å °é ”**. I opened another one and did the same search again and this time the error didn't happen. I might have done something prior that triggered it. My Chinese input module is [OpenVanilla](https://openvanilla.org/) if this matters.

![screen shot 2019-01-08 at 13 44 30](https://user-images.githubusercontent.com/46397851/50811986-d9428100-134b-11e9-98b3-003673ec39fd.png)

**Comment by PalmerAL** [comment]
I've modified the searchbar in 32cd443cda9c255bf636662b50a22f6eb055f9f5 to use `event.key` instead of keyCode, which should hopefully help with the first and second issues (although I'm not entirely sure). If that doesn't work, we'll probably need to use the `beforeinput` event instead, although the fact that it [isn't cancellable](https://github.com/w3c/input-events/issues/92) means it'll be trickier to make autocomplete still work.

The third issue is also fixed in 1.10 - if you hover over an entry in the bookmarks list, you'll see a delete button for that item.
