### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by JGSangara** [minbrowser/min#705]
Anyone assist me on how i can use the Min adblock on my custom electron app.

**Comment by PalmerAL** [comment]
The code for the adblocker is here: https://github.com/minbrowser/min/blob/master/ext/abp-filter-parser-modified/abp-filter-parser.js. In order to use it, you would need to include that file in your app along with a filter list, and then use the provided API's to load a filter list and check URL's against it. You can see an example of how to do that here: https://github.com/minbrowser/min/blob/master/main/filtering.js.

In particular, this is where the filter list is loaded: 
https://github.com/minbrowser/min/blob/827fe36c1d16b527688996a32e150981603160ef/main/filtering.js#L13-L26

And this is where the URL's are checked: https://github.com/minbrowser/min/blob/827fe36c1d16b527688996a32e150981603160ef/main/filtering.js#L82-L85

That code gets run inside of an onBeforeRequest listener, which is described here: https://electronjs.org/docs/api/web-request#webrequestonbeforerequestfilter-listener

**Comment by JGSangara** [comment]
Thanks.
