### ISSUE TITLE
Why is com.screencastomatic installed

### ISSUE THREAD

**Issue by imagercaz** [minbrowser/min#712]
I have found when I start min com.screencastomatic folder is installed on my system.  If I delete the folder it comes back when I start MIN again.  I  believe this is used for screen recording and wondered why it is installed in MIN
<img width="2048" alt="screen shot 2019-02-15 at 5 51 51 am" src="https://user-images.githubusercontent.com/44264379/52857966-0ec65100-30e6-11e9-87a0-98942c72bd0e.png">

**Comment by PalmerAL** [comment]
What's the full path to that folder?

I don't have a folder with that name on my computer, and I haven't been able to find anything like that in the Min binary. There is an app named [Screencastomatic](https://screencast-o-matic.com/) - is there any chance that you've installed that at some point?

**Comment by imagercaz** [comment]
This is a new computer and have never installed Screncastomatic.  The first thing I did was to their website and check them out.  When I delete the folder is only reappears when I start up MIN.  I tried opening all other app and it does not appear.

I think this is what you want, but if it is not let me know what you need.   Screencastomative does not appear in this title but show up as that in app cleaner pro.  Is that app wrong?  It’s final name is net-export.


Macintosh HD⁩ ▸ ⁨private⁩ ▸ ⁨var⁩ ▸ ⁨folders⁩ ▸ ⁨zg⁩ ▸ ⁨yw33dqxd5fdf2vxpfx0hmdpc0000gn⁩ ▸ ⁨T⁩

**Comment by PalmerAL** [comment]
Thanks, that is helpful.

I'm still not entirely sure what's going on, although I'm leaning towards that app identifying Min wrong. There is a reference to a "net-export" file inside the Electron framework, specifically this:
```
net-export/chrome-net-export-log.json
```
Which is a file that is [part of Chromium](https://cs.chromium.org/chromium/src/chrome/browser/ui/webui/net_export_ui.cc?q=net-export-log&sq=package:chromium&g=0&l=241).

That file shouldn't actually be created unless you enable network logging (which is off by default), but I suppose it's possible it's being enabled somehow.

Because of [Gatekeeper App Translocation](https://lapcatsoftware.com/articles/app-translocation.html), macOS will initially copy Min to a folder in `/private/var/folders` and run it from there until you move it to a different location; for example, if I download a new copy of Min it gets run from here:
```
/private/var/folders/l4/q7gr5nt154lbfrsyngfx9bcc0000gn/T/AppTranslocation/F385FFE3-B162-4961-A042-AA25373054BF/d/Min.app/Contents/Resources/app
```
so the `⁨yw33dqxd5fdf2vxpfx0hmdpc0000gn⁩` folder is probably the folder that contains all of Min's files in it.

So I think this is a false positive - either the app is looking at the Min binary and finding the `net-export` string within it, or we're creating a net-export-log for some reason and it's identifying that. Just to make sure, could you open the `net-export` file that you're seeing, and post the contents of it here?

**Comment by imagercaz** [comment]
I created the file again, and check it has zero bytes per the file info.  I also looked inside and it does appear to be empty.  I will leave the file for now, use MIN and check again in a few days and see if anything shows up and let you know.

Just wanted to let you know I love MIN.

**Comment by imagercaz** [comment]
Still no info in the folder so it is probably not a concern, deleting it does not cause any issues.   But whenever a folder is created called net-export it sets off alarm bells.  


Thanks

Lars Olsen

**Comment by dbfreem** [comment]
No one has commented on this one since Feb. This one can probably be closed.

**Comment by imagercaz** [comment]
The most recent version of Min no longer creates the file,  

It can be closed
