### ISSUE TITLE
Freeze when going fullscreen on a new tab

### ISSUE THREAD

**Issue by PluckyJokerhead** [minbrowser/min#721]
If you press F11 when on a blank tab the whole browser freezes (at least it does for me). Only way to recover is by killing the browser and opening again.

**Comment by PalmerAL** [comment]
Thanks for reporting this!

This is kind of a silly bug. What's happening here is that there's two types of fullscreen: either the entire UI can be in fullscreen mode, or just the page contents can be in fullscreen. [windowsCaptionButtons.js](https://github.com/minbrowser/min/blob/master/js/windowsCaptionButtons.js) uses a variable called `windowIsFullscreen` to keep track of the first case, and update the window buttons accordingly, but [webviews.js](https://github.com/minbrowser/min/blob/master/js/webviews.js), which keeps track of the second type of fullscreen, uses the same name, and because these both run in the same scope, the two variables end up overwriting each other. So when you put the window in fullscreen mode, `windowIsFullscreen` will become true, so webviews.js will think that the tab you have open should be in fullscreen, and resize the (empty) tab so that it fills up the entire window. And because empty BrowserViews ignore any keyboard events, there's no way to exit from fullscreen mode again.

I've fixed this in 0cb1b42b9a54202ed8c18bd19b536e928763323e by changing the name to something else that doesn't conflict. Eventually, the plan is to split different components like this into modules (#307), so that re-using the same variable name twice won't result in conflicts.
