### ISSUE TITLE
how to control webview use ipc?

### ISSUE THREAD

**Issue by hanxiao123** [minbrowser/min#768]
I  access my website(http)   use min,It's a html page,I need some script code to do some function such as addNewTab,closeWebview,I know Ipc can do it in electron , but how to do it  in min?thank you!!!

**Comment by PalmerAL** [comment]
Can you explain more specifically what you're trying to do?

There are built-in JS functions (in every browser) that let you open and close tabs - `window.open` and `window.close`. That may be enough to do what you want, and you wouldn't have to make any changes to Min to do that.

Otherwise, you need to add an IPC handler (like you mentioned) to let you access the UI code. Since the preload script runs in a separate context, you would need to use `postMessage` to do that. Here's an example of something you could add to the preload script (js/preload/default.js):

```
window.addEventListener('message', function (e) {
  if (e.data === 'example-message') {
    ipc.send('example-message')
  }
})
 electron.webFrame.executeJavaScript(`
  window.example = function () {
    postMessage('example-message', '*')
  }
`)
```

Once you do this, you can call `window.example()` from inside your webpage, and it wil send an IPC message to the UI process.

Then, you could add a handler in the UI process (either in js/default.js, or in some other file):

```
webviews.bindIPC('example-message', function (webview, tabId, args) {
  //do something here
})
```

Be pretty careful when doing this however - this function will be exposed to whatever webpage you load, so it's easy to accidentally create security issues if you give webpages access to the wrong things.
