### ISSUE TITLE
Option to Disable Dark Mode

### ISSUE THREAD

**Issue by janaabpakaal** [minbrowser/min#807]
Let me tell you, this is a great web browser and I am very happy with it,but I have two issues 
1.During Dark Mode ,Websites are difficult to read and would like option to disable it.
2.I would like to stay on current page when i rt click and open links on the websites in tabs. 
![min-darkmode](https://user-images.githubusercontent.com/54422502/63557684-5206ee00-c567-11e9-9ab4-babb46f5f2a0.png)
![min-darkmode2](https://user-images.githubusercontent.com/54422502/63557754-a3af7880-c567-11e9-989c-b3b6fa102a40.png)

**Comment by PalmerAL** [comment]
Thanks for reporting this! This looks like a bug in Electron; what's supposed to happen is that the new tab page uses a dark background, and then the background changes to white once a page is loaded. Since this isn't working, I've disabled it for now (c866c461694d66a5bb1e6efb5ac92f9fc83d33f7) until this can be fixed in Electron.

There's an existing issue open for the second item: #60.

**Comment by PalmerAL** [comment]
I'll probably release an update in the next week or two with the fix for this; in the meantime, if you open this file: `/usr/lib/min/resources/app/css/webviews.css`, and change this line: 
`.dark-mode #webviews {`
to this:
`body:not(.linux) .dark-mode #webviews {`
it should work.

There's also another issue open about disabling dark mode entirely #286 (although it shouldn't matter as much if the pages are readable).

**Comment by benstandaert** [comment]
This is fixed in the latest release: https://github.com/minbrowser/min/releases/tag/v1.11.1

**Comment by PalmerAL** [comment]
This is fixed in the latest release: https://github.com/minbrowser/min/releases/tag/v1.11.1
