### ISSUE TITLE
How to proceed with Settings

### ISSUE THREAD

**Issue by burnoutberni** [minbrowser/min#81]
I'd like to contribute a couple of things, for example a setting to disable the swipe gestures, but where should I put it? Are the privacy settings a separate settings page on purpose, or did that just happen, because there were no other settings? Can I just change the name of privacy settings to settings and add a couple of more items or should I create another settings page?

**Comment by PalmerAL** [comment]
Yes, that was just because there weren't any other settings. Adding other settings is fine. There probably needs to be an API for settings first, like https://github.com/PalmerAL/min/blob/master/pages/settings/settings.js#L70 but that also caches settings in-memory.

I think it would be good to avoid having settings if possible, though, and instead figure out if the default can be changed. For example, with the swipe gestures, it's probably better to adjust them so they accidentaly trigger less rather than creating a setting to turn them off.

**Comment by jkanarek** [comment]
I  was planning on sketching something out soon. WIll post here.

**Comment by PalmerAL** [comment]
I've added a settings API in 3b9db2939e2ceaf3e0303b167909e1a36467cebb. Usage:

```
settings.get(key, function(value) {
});

settings.set(key, value);

settings.delete(key);

```

**Comment by PalmerAL** [comment]
A settings page was added several versions ago, so I don't think there's any reason to have this issue open any longer.
