### ISSUE TITLE
there's no 1.11- i368 version?

### ISSUE THREAD

**Issue by dmbarrad** [minbrowser/min#810]
i'm runing a 32bit laptop, and i didn't find your 1.11 i368 version?
is it no longer supported ?

**Comment by PalmerAL** [comment]
Electron [removed support for 32-bit Linux](https://electronjs.org/blog/linux-32bit-support) a while back, so 1.9.2 is the last release of Min that will work on 32-bit; sorry!

I believe the latest version of Firefox still supports 32-bit, so that's probably your best option for continuing to use a current browser.

**Comment by coder963** [comment]
will it work on 32 bit windows system?

**Comment by PalmerAL** [comment]
Yes. I'm not sure if the installer will work, but if it doesn't there's a 32-bit zip file.
