### ISSUE TITLE
Jira error

### ISSUE THREAD

**Issue by ZZYYYKK** [minbrowser/min#816]
The page does not load. Disabling ad blocking does not help

**Comment by PalmerAL** [comment]
I can't reproduce this, can you please provide more information:

* Please provide the exact URL this is happening on.
* Next, open the network tools (developer > inspect page > network), then reload the page, and click the "download" icon near the top. Save that file, and attach it to this issue.

**Comment by ZZYYYKK** [comment]
[1.har.zip](https://github.com/minbrowser/min/files/3652680/1.har.zip)

**Comment by ZZYYYKK** [comment]
<img width="1792" alt="Screenshot 2019-09-25 at 16 11 12" src="https://user-images.githubusercontent.com/26084800/65604991-035ad280-dfb1-11e9-9e3f-930436af82e8.png">

**Comment by ZZYYYKK** [comment]
![Screenshot 2019-09-25 at 16 11 23](https://user-images.githubusercontent.com/26084800/65605039-179ecf80-dfb1-11e9-99e2-07234d8027a7.png)

**Comment by PalmerAL** [comment]
It looks like the network inspector didn't capture anything for some reason, can you try this instead?

* Go to developer > inspect page > console
* paste this:
```
new URLSearchParams(window.location.search).get("ec")
```
 and post the result here.

Also, did you add the spaces for redaction, or were they part of the original url?

**Comment by ZZYYYKK** [comment]
I closed the company in which I work with spaces. This is a corporate service and I was a little safe, as required by the company :)

**Comment by ZZYYYKK** [comment]
[umail.company.com.har.zip](https://github.com/minbrowser/min/files/3662046/umail.company.com.har.zip)

**Comment by ZZYYYKK** [comment]
[sso.company.com.har.zip](https://github.com/minbrowser/min/files/3662074/sso.company.com.har.zip)
I'm sorry, got confused in the posts

**Comment by PalmerAL** [comment]
What normally happens when you load this page in another browser? Do you get a form where you have to enter your username and password, or does it sign you in automatically? Do you know if you or your IT department did anything special to configure those browsers? Does the login only work in certain browsers?

I know almost nothing about how Microsoft's authentication system works, but from looking at the SSO log and after doing some research:

* After loading the auth page, you get redirected to https://sso.company.com/adfs/ls/wia, which corresponds to the URL for "windows integrated authentication". From [here](https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/integrated-windows-authentication):
> Integrated Windows authentication enables users to log in with their Windows credentials, using Kerberos or NTLM. The client sends credentials in the Authorization header. Windows authentication is best suited for an intranet environment

The server sends a 401 response, indicating it needs some kind of authentication, along with these headers:
```
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
```
"Negotiate" defaults to Kerberos, then NTLM. I'm still not entirely clear how either of these work, but it looks like in both cases, you somehow have to pass the local Windows credentials to the server.

* For NTLM, you have to specially configure Chrome: https://specopssoft.com/blog/configuring-chrome-and-firefox-for-windows-integrated-authentication/. Electron has a [similar option](https://electronjs.org/docs/api/session#sesallowntlmcredentialsfordomainsdomains), so I guess we would need to add an option for that.
* It looks like Chrome has a similar process: http://woshub.com/enable-kerberos-authentication-in-browser/#h2_2.
* [This article](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-browser-wia) suggests that you have to manually enable each browser you want to support from the Active Directory admin interface. That could be it, but it looks like it's user-agent based, and we use the same user agent as Chrome, so I'm guessing that's not the issue.


If it's true that your IT department has configured other browsers somehow to support this (which I'm guessing is the case), I think the best bet is to find out what that configuration is, and see if we can do the same thing. If there's not any special configuration, then I don't really have any idea.

It might also be useful to test whether this works when you're not on your internal company network, since accessing the site from outside there should use a different authentication method.

**Comment by PalmerAL** [comment]
BTW, the network logs had the name of your company in them, so I deleted your previous comments.

**Comment by ZZYYYKK** [comment]
In other browsers, when the page loads, a request for a username and password.
If I am not in the corporate network, then I am use vpn. Chrome and many browsers based on it, as well as firefox and safari work out this scenario out of the box.
Unfortunately, I will not be able to provide more detailed information about the SSO settings.

**Comment by Syndamia** [comment]
It doesn't seem like we'll be able to do any investigation, also there is a chance this is caused by some specific company configuration.
