### ISSUE TITLE
window is hidden and error on Window-Close

### ISSUE THREAD

**Issue by DrGo** [minbrowser/min#825]
Min Version 1.11.0 (1.11.0) on MacOS 10.15 Beta (19A558d), 
closed 3 windows; one was playing youtube video. But I could still hear the video playing. tried to use Window-Close menuitem and got the error below. Had to quit the app.

Uncaught Exception:
TypeError: Cannot read property 'isFocused' of null
    at click (/Applications/Min.app/Contents/Resources/app/main.build.js:389:31)
    at MenuItem.click (/Applications/Min.app/Contents/Resources/electron.asar/browser/api/menu-item.js:48:17)
    at Function.executeCommand (/Applications/Min.app/Contents/Resources/electron.asar/browser/api/menu.js:32:17)

**Comment by PalmerAL** [comment]
Thanks for reporting this! This was due to a couple of fairly silly issues:

* Open tabs weren't actually being destroyed when you close the window, because the app only has one window, and it's assumed that you'll close the app rather than the window.
* The close menu item wasn't checking to see whether there was actually a window open.

Both of these are fixed in a813acf59aa312916192c4100a937cd87a9954c8; I'll make a new release soon with these changes.

**Comment by DrGo** [comment]
Thank you

**Comment by benstandaert** [comment]
This is fixed in the latest release: https://github.com/minbrowser/min/releases/tag/v1.11.1

**Comment by PalmerAL** [comment]
This is fixed in the latest release: https://github.com/minbrowser/min/releases/tag/v1.11.1
