### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by YamiteruXYZ** [minbrowser/min#826]
Is there any sync with my Google bookmarks and passwords? I couldn't find it so I believe this feature is not integrated. Are you planning on integrating it? I love Min, but without this I'm not gonna use it, because I have so many bookmarks and more importantly passwords saved on my Google account.

**Comment by PalmerAL** [comment]
You're right there isn't a way to sync currently. I'm not sure if bookmarks sync will happen anytime soon, because I'd like to avoid running our own servers for it, but we might be able to integrate with dropbox/google drive/something else to do that. 

For password sync, there's some work happening in #822 to support third-party password managers with Min, so it should be possible to sync your passwords that way once that's completed.

**Comment by YamiteruXYZ** [comment]
Thank you for info 👍
