### ISSUE TITLE
Default search engine does not survive on app quit

### ISSUE THREAD

**Issue by Lacedaemon** [minbrowser/min#849]
I've changed my default search engine from DuckDuckGo to Google.  The setting persists during the session, but as soon as I close / reopen the app, it's back to using DuckDuckGo.

When I go to the Settings page after reopening the app, the default search engine is still set to Google, but any searches typed into the address bar go to DuckDuckGo.  Changing the search engine to anything else, then back to Google, gets it working again for the session only.

- Min version: Latest build from source
- OS version: macOS Catalina 10.15.1

The app is installed to /Applications.

I've tried using FreeMacSoft's AppCleaner to purge any Min-related files to start fresh.  Still no dice.

I've also noticed this on my other two machines: one on macOS Catalina, and the other on Solus Linux.  Both were compiled from source as well.

Thanks!

**Comment by PalmerAL** [comment]
Thanks for reporting this! Fixed in 68eafc10c4cecd5a39fea927b009c13b0ed96bb0.

Previously, searchEngine.js depended on settings.initialize() being called before it would run, which worked because settings was loaded before it in default.js. However, #832 changed this order by loading dbMigration.js before settings.js (and dbMigration depends on places.js, which depends on searchEngine). So when searchEngine loaded initially, the settings wouldn't have been initialized, so it would assume no search engine had been set. The fix here is to make settings.js initialize itself whenever it is loaded, so that the modules don't have to be loaded in a particular order.
