### ISSUE TITLE
Tab Title

### ISSUE THREAD

**Issue by muhakmalfadh** [minbrowser/min#859]
some tab title is bright when that tab wasn't opened.
i think the bright tab title should be for the opened one and the rest was darker.

![image](https://user-images.githubusercontent.com/31181467/69028168-b967f900-0a03-11ea-85a9-732e7bef7d33.png)

**Comment by PalmerAL** [comment]
Interesting idea! I can see how that would make it easier to see which tab is selected. However, on some background colors, it seems like it would make the titles of the inactive tabs harder to read than they should be.

Currently, whether or not a title is bright depends on how recently you opened the tab; I think it is useful to have some way to distinguish between recently-viewed tabs and older ones.

**Comment by dj-sash** [comment]
Hi… PalmerAL. Can you give some Preferences options to handle the Min Browser?
Look I am just a designer and I am really null in coding and I know only macOS.
Some options like: To choose the Fix Colors of Selected Tab (active) and the other Tabs Behind. Because I am not understanding. It something changes colors from All Dark to All Pale Grey. Yet the Active and Behind tabs colors are so close that it is difficult to confirm which one is selected.

2. I do not want that address to appear whenever I click on the Tab. Can you do it like, to see the URL address, it should be DOUBLE CLICKED? Because right now, in a Single Click on the Tab, because of the Color confusion, as I click on the Tab, here it goes showing me the root list of my browse to the actual webpage. It is seriously confusing.
Or you just make the Address Bar above, the tabs below in 2 lines. Or you load an option like to see the List and web address, you have to double click in the tab.
3. And also, If you give a Separate Address Bar, it would be so superb to add some ICONS which everyone finds very important; Home Page, Downloads, History, Bookmarks, Refresh, Forward, Backward. These are really basic icons in browsing.

Please do understand we are mac users, not really pro in these coding stuff. And your browser is super fast. That would be the number 1 in browsers if you load what I am requesting you above.

I already asked you once. But, Im still finding nothing done.

I do not know how to talk to you, except from sending a message here.

Let me know, if what I am requesting can be done.

Thanks again.

**Comment by Syndamia** [comment]
Closing, because it's better to discuss it in #1047.
