### ISSUE TITLE
Question with focus mode

### ISSUE THREAD

**Issue by aurelienprovenchere** [minbrowser/min#865]
Sorry, 
I don't know how to post  question.
I just want to know what is the keyboard shortcut for focus mode ? 

Thank you !

**Comment by PalmerAL** [comment]
There isn't a shortcut for focus mode. Originally, the thinking behind that was that introducing a small delay to switch in and out of focus mode is good, because it makes you stop for a second and choose to focus on something. But I suppose we could add a shortcut, and just make it editable so that you can disable it.
