### ISSUE TITLE
How to update the browser if I installed it using pacman?

### ISSUE THREAD

**Issue by talentlessguy** [minbrowser/min#879]
Currently min shows a message that there is an update but I can't do anything because I installed it via pacman.

Are there any plans to update min for Arch Linux?

Or maybe ship `pacman` target to releases.

Currently the only way to use Min for me, is cloning and building, which is not very comfortable

**Comment by PalmerAL** [comment]
What version do you have installed? The update notification is only showing right now for versions <1.11.2, but the latest Arch package was 1.11.2 when you opened this issue (and has since been updated to 1.12.0), so you should be able to get the latest version.

There's also an option to disable the notification (preferences > check for updates) if you need to, but you shouldn't have to do that.

**Comment by talentlessguy** [comment]
@PalmerAL I'm using 1.12.0, it still shows, but there's no update for Arch. the only way is to build from source. Maybe it's also worth shipping `.pacman` file to release, if updating the registry is problematic :thinking: ?

**Comment by PalmerAL** [comment]
The arch repository has the latest version: https://www.archlinux.org/packages/community/any/min/, is that the package you're using?

**Comment by talentlessguy** [comment]
@PalmerAL oopsie, my mirror list is outdated, sorry for interrupting
