### ISSUE TITLE
Turn off zooming with "CMD + <scroll>"

### ISSUE THREAD

**Issue by Vilscon** [minbrowser/min#89]
I use the command tab a lot, but I also scroll a lot. Whenever I just scrolled a bunch and press CMD + TAB to move to a different window, for example, the whole page gets zoomed in.

This should either be turned off or they should be a way to capture the difference between these moments. I mean, even if the page is stopped scrolling, the scrolling momentum is staying alive and will zoom the page when you press the CMD button.

**Comment by abejfehr** [comment]
I now see why this is happening, but I can't think of a good fix.

The [`wheel`](https://github.com/minbrowser/min/blob/d1db4753aff7f4a8c038c1ef54371714e95a6cc9/js/webview/swipeEvents.js#L38) event being captured seems to fire repeatedly on macOS until the momentum from the scroll is gone, which can be seen [here](https://jsfiddle.net/38u9yjdL/).

I thought that a valid alternative would be to use the `scroll` event, but that wouldn't be accurate either, since even if the window isn't scrolling, some element inside of it could be. I've illustrated that [here](https://jsfiddle.net/38u9yjdL/1/).

Does anyone have any ideas?

**Comment by revolter** [comment]
A very easy solution would be to add a preference setting that disables it, as you can also use <kbd>cmd</kbd> + <kbd>+</kbd>.

**Comment by PalmerAL** [comment]
It looks like electron has a <a href="http://electronjs.org/docs/api/browser-window#event-scroll-touch-end-macos">```scroll-touch-end```</a> event that could work. The only issue would be that it fires in the main process, so we would be sending a lot of IPC messages to the window, which might not perform very well.

**Comment by PalmerAL** [comment]
Another way we could fix this would be to check whether the command key is pressed at the beginning of the scroll gesture (we could probably reuse the swipeGestureTimeout for this). If the key isn't pressed at the beginning of the gesture, then we wouldn't zoom even if it is pressed later on in the gesture.

**Comment by revolter** [comment]
Sounds good. Will you start working on it? I could test it if you want.

**Comment by PalmerAL** [comment]
I can do it if you want, I don't think it will be too difficult.

**Comment by PalmerAL** [comment]
@revolter PR is here: #534.
