### ISSUE TITLE
Atom package/extension support?

### ISSUE THREAD

**Issue by dlobue** [minbrowser/min#907]
Since Atom (and vscode, now that I think about it) are based on electron, is it possible to use their extensions in min? I'm thinking of plugins like vim-mode-plus: https://atom.io/packages/vim-mode-plus

If so, Min could be the perfect replacement browser all of us still using FF just so we can use pentadactyl. Being able to modify the UI and having the vim layer be above the web view layer would be game changing!

**Comment by PalmerAL** [comment]
Supporting Atom packages likely wouldn't be any easier than supporting normal Chrome extensions, and since most of the Atom API's are designed for a text editor, it's not obvious what they should do inside a browser.

There's an issue open about Vim-mode support in Min here: #37; you can do some of this already:

* You can modify all of the shortcuts listed in preferences to be single letters, and they should work as expected.
* I wrote a userscript that implements link selection from the keyboard: https://gist.github.com/PalmerAL/a32a7fc60913e641e621b76c2339d8c2.

I'd generally be fine with adding more options for shortcuts if you have ideas; we could probably also have a default vim-mode set of shortcuts that you could enable without having to set each shortcut manually.
