### ISSUE TITLE
long term goals?

### ISSUE THREAD

**Issue by lxle** [minbrowser/min#958]
planning on hanging around for a while?  don't want to commit to a new browser if it's a gone in a year type of project.

**Comment by PalmerAL** [comment]
I don't have an exact answer to that unfortunately; I certainly intend to continue working on this project, but at the moment I'm not sure what I'm going to be doing a year from now or how much time I'm going to have. However, I will say that:

* Electron (which this project is based on) is almost certainly going to keep releasing updates, so even if development on this project slows down (which I'm not necessarily saying will happen), you can expect to keep receiving Chromium updates and bug fixes.
* It's fairly easy to export your data so that you're not locked into the browser. Passwords are all stored in an external password manager, and there's an option to export your bookmarks as an HTML file that you can import into any other browser.
