### ISSUE TITLE
Is there a way to save my open tabs and/or bookmarks without having access to Min?

### ISSUE THREAD

**Issue by richbordoni** [minbrowser/min#967]
So, to make a long story short, I borked my bootloader trying to set up dual-boot with another OS and can no longer boot into my Windows install. I still have access to all of my data though so I was wondering if there was any way to possibly pull some files from Min's user profile folder that will let me save my open tabs and/or bookmarks?

I already pulled two files, "sessionRestore.json" and "sessionRestoreBackup-1580858144708.json" (the only two sessionRestore files I found). Will those enable me to restore my open tabs in a new install of Min? And is there any file or folder that I could possibly recover my bookmarks from?

Thanks!

**Comment by PalmerAL** [comment]
sessionRestore.json alone should be enough to get your open tabs back; the backup file isn't likely to be helpful, since it was created in February.

Bookmarks and history are stored a database in the IndexedDB/file__0.indexeddb.leveldb directory, so copying that folder should work.

If you're able to, it might be easier to just copy the entire profile folder and restore that.

**Comment by richbordoni** [comment]
Awesome, thank you very much for the response. 😊 

> just copy the entire profile folder

And yes that sounds like the best course of action!
