### ISSUE TITLE
How can I delete cookies?

### ISSUE THREAD

**Issue by Retriev3r** [minbrowser/min#990]
Hi!
First of all I love Min, the simplicity is really genius ;)

How can I remove cookies? 
The command !clearhistory does not seam to help ¯\_(ツ)_/¯ 
And I've found nothing else.
I am on macOS Version 10.13.6 (High Sierra).

+ is it possible to turn "do not track" setting on?

Thank you!
Ben

**Comment by PalmerAL** [comment]
Thanks!

There isn't any way to delete cookies from the UI at the moment; I agree `!clearhistory` should probably do that, and it looks like it would be fairly simple to add.

There isn't a setting for do-not-track, but since very few sites actually support it, turning it on won't have much of an effect. I think the existing settings for blocking trackers should be sufficient for that.

**Comment by Retriev3r** [comment]
Ok, thank you.
I am looking forward to the new improved !clearhistory  ;) 
I guess I have to remove the app and re-install it, for now (to remove cookies).

**Comment by PalmerAL** [comment]
I think you can also find your profile folder ( ~/library/application support/min on Mac, \users\username\appdata\roaming\min on Windows, /home/username/.config/min on Linux) and delete the `cookies` and `cookies-journal` files.

**Comment by PalmerAL** [comment]
Fixed in 83c9887972b2af0551da309de1dbb9af51196271.
