### ISSUE TITLE
hackernoon.com doesn't open error code: -355.

### ISSUE THREAD

**Issue by deadb0d4** [minbrowser/min#992]
It is a strange glitch I encountered: the site seems to open but then crashes and prints the error code -355.

**Comment by deadb0d4** [comment]
My operating system is latest macOS, but I think it should be reproducible for all OS's.

**Comment by PalmerAL** [comment]
I can actually reproduce this in Chrome as well; if I clear the cache and try to load the page, it never finishes loading and I get the same error (ERR_INCOMPLETE_CHUNKED_ENCODING), but subsequent loads work fine. So I think it's probably a site issue.

**Comment by deadb0d4** [comment]
> I can actually reproduce this in Chrome as well; if I clear the cache and try to load the page, it never finishes loading and I get the same error (ERR_INCOMPLETE_CHUNKED_ENCODING), but subsequent loads work fine. So I think it's probably a site issue.

That is strange. At the very least the page still opens in Safari, Firefox and Chrome at my laptop.

**Comment by PalmerAL** [comment]
At least in Safari and Chrome, I think it depends on whether the site is still in your browser cache or not. If I open a new private window and go to to the site, it will fail on the first load almost every time, but it works after reloading it.

It does seem to work every time in Firefox.

In Min, subsequent loads seem to fail just as often as the initial loads (maybe 80% of the time). I wonder if that's because we're redirecting to an error page, rather than just showing a blank page like other browsers do (but I'm not sure how that would make the failure condition happen more often).

**Comment by Syndamia** [comment]
@deadb0d4 are you still having this issue? I reloaded the site a couple of time and it worked fine every time.

**Comment by deadb0d4** [comment]
> @deadb0d4 are you still having this issue? I reloaded the site a couple of time and it worked fine every time.

No, everything is fine at least with `hackernoon.com'.

**Comment by deadb0d4** [comment]
Thanks for your replies.
