### ISSUE TITLE
Hide the menu when the system title bar is used

### ISSUE THREAD

**Issue by Retrotux** [minbrowser/min#995]
Hey @PalmerAL , first of all, thank you for this awesome browser! I'm currently running elementaryOS (based on Ubuntu). For consistency, I would like to use the system title bar. In earlier releases, you could hide the menu bar with the shortcut ctrl+m., but this is no longer possible. Could you reactivate this functionality?

**Comment by PalmerAL** [comment]
I'd like to avoid having too many configurations for the title bar, since each one makes the code harder to maintain, but I think there's a couple options we could do:

1. We could possibly detect that you're running Elementary, and move the window buttons to the left (https://github.com/minbrowser/min/issues/984#issuecomment-621727750) - would that help avoid the need to use the native titlebar?
2. We could just make the menu button the default, even if you're using the native title bar. I actually can't think of a big reason not to do this, although some people might prefer the traditional layout.

**Comment by Retrotux** [comment]
Personally, I would prefer option 2, because there are some advantages of using the system title bar in Linux distributions:

1. There's a great variety of different window button layouts on Linux. The default layout in elementaryOS, for example, is a close button on the left and a maximize button on the right with no minimize button at all. Because this is inconvenient for me, I tweaked it to resemble the OS X-layout. By using the system title bar, you can avoid dealing with different distributions and still make Min fit in every UI.
2. I tried to use Min without the system title bar, but found it difficult to control the window with drag and drop, which I use quiet frequently. The system title bar makes it easy to do that.
3. The system title bar adheres to the set GTK theme and simply looks good (but this more a nice to have than a real issue).

**Comment by PalmerAL** [comment]
Fixed in 1216549f944802028d1d67345c133b3089d35d07:

<img width="1128" alt="Screen Shot 2020-05-04 at 1 58 41 PM" src="https://user-images.githubusercontent.com/10314059/81003153-043dc780-8e10-11ea-9d99-e04fa5e93f46.png">
